[workspace]
resolver = "3"
members = [
  "example",
  "wbase",
  "wbftree",
  "wcompact",
  "wcpr",
  "wdev",
  "wepoch",
  "whasher",
  "whlog",
  "windex",
  "wkv",
  "wram",
  "wrecord",
  "wreviv", "wutil",
  "wval",
  "wserver", "wobject", "waof", "wacl",
]

[workspace.dependencies]
bf-tree = "0.5.6"
bitcode = "0.6.9"
coarsetime = "0.1.37"
compio = "0.19.2"
compio-buf = "0.8.3"
crc32fast = "1.5.1"
fastrand = "2.5.0"
gxhash = "3.5.0"
itoa = "1.0.18"
libc = "0.2.189"
log = "0.4.34"
papaya = "0.2.5"
parking_lot = "0.12.5"
serde = "1.0.229"
sonic-rs = "0.5.8"
strum = "0.28.0"
thiserror = "2.0.20"
zmij = "1.0.23"
aok = "0.1.18"
ctor = "1.0.13"
log_init = "0.1.39"
tempfile = "3.27.0"

[workspace.dependencies.wbase]
version = "0.1.2"
path = "wbase"

[workspace.dependencies.wbftree]
version = "0.1.1"
path = "wbftree"

[workspace.dependencies.wcompact]
version = "0.1.0"
path = "wcompact"

[workspace.dependencies.wcpr]
version = "0.1.0"
path = "wcpr"

[workspace.dependencies.wdev]
version = "0.1.1"
path = "wdev"

[workspace.dependencies.wepoch]
version = "0.1.1"
path = "wepoch"

[workspace.dependencies.whasher]
version = "0.1.4"
path = "whasher"

[workspace.dependencies.whlog]
version = "0.1.1"
path = "whlog"

[workspace.dependencies.windex]
version = "0.1.0"
path = "windex"

[workspace.dependencies.wram]
version = "0.1.3"
path = "wram"

[workspace.dependencies.wrecord]
version = "0.1.1"
path = "wrecord"

[workspace.dependencies.wreviv]
version = "0.1.0"
path = "wreviv"

[workspace.dependencies.wval]
version = "0.1.0"
path = "wval"

[workspace.dependencies.futures-util]
version = "0.3.34"
default-features = false

[workspace.lints.clippy]
arc_with_non_send_sync = "allow"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
