[package]
name = "wclient"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/wclient"
description = "wclient"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
compio = { workspace = true, features = ["net", "io", "runtime"] }
crossfire = "3.1.20"
itoa.workspace = true
log.workspace = true
memchr = "2.8.3"
thiserror = "2.0.20"
wepoch = { version = "0.1.1", path = "../../embed/wepoch" }
zmij = "1.0.23"

[dev-dependencies]
aok = "0.1.18"
ctor = "1.0.13"
log = "0.4.34"
log_init = "0.1.39"

[lints]
workspace = true
