[package]
name = "windex"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb_base.git"
homepage = "https://github.com/webc-site/wedb_base/tree/main/windex"
description = "windex"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
thiserror = { workspace = true }
wbase = { workspace = true, features = ["addr"] }
whasher = { workspace = true }
wram = { workspace = true }

[dev-dependencies]
aok = { workspace = true }
ctor = { workspace = true }
log = { workspace = true }
log_init = { workspace = true }

[lints]
workspace = true
