[package]
name = "windex"
version = "0.1.2"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/windex"
description = "Lock-free fixed-capacity hash index with overflow bucket pool"
keywords = ["hash-index", "lock-free", "hash-table", "storage-engine", "concurrency"]
categories = ["database-implementations", "data-structures", "concurrency", "algorithms", "memory-management"]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
thiserror = { workspace = true }
wbase = { workspace = true, features = ["addr"] }
whasher = { workspace = true }
wram = { workspace = true }

[dev-dependencies]
aok = { workspace = true }
ctor = { workspace = true }
log = { workspace = true }
log_init = { workspace = true }

[lints]
workspace = true
