use crate::txn::{BatchOp, TxnReq};
use wedb_embed::sortedint::SortedintRangeSpec as SortedIntRangeSpec;

/// 字段过期条件（对标 Apache Kvrocks HashFieldExpireCondition）
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, bitcode::Encode, bitcode::Decode)]
pub enum ExpireCondition {
  #[default]
  None,
  NX,
  XX,
  GT,
  LT,
}

/// 解析出来的完整 Redis 命令枚举（涵盖 Kvrocks 331+ 全套接口与 WebDB 分布式 Raft 接口）
#[derive(Debug, Clone, PartialEq)]
pub enum Cmd {
  // ================= 1. 连接、鉴权与命名空间管理 =================
  Ping(Option<String>),
  Echo(String),
  Info(Option<String>),
  Role,
  Select(u64),
  Command,
  ConfigGet(String),
  ConfigSet(String, String),
  Time,
  ClientId,
  ClientGetName,
  ClientSetName(String),
  ClientList,
  ClientInfo,
  ClientKill(Vec<String>),
  ClientPause(u64),
  ClientUnpause,
  ClientUnblock {
    id: i64,
    unblock_type: Option<String>,
  },
  ClientTracking {
    enable: bool,
    client_id: Option<i64>,
    prefixes: Vec<String>,
    bcast: bool,
    optin: bool,
    optout: bool,
    noloop: bool,
  },
  ClientTrackingInfo,
  ClientGetRedir,
  ClientSetInfo(String, String),
  ClientNoTouch(bool),
  ClientNoEvict(bool),
  ClientReply(String),
  ClientHelp,
  Hello(Option<u8>),
  Quit,
  Auth {
    username: Option<String>,
    password: String,
  },
  NamespaceAdd(String, String),
  NamespaceSet(String, String),
  NamespaceDel(String),
  NamespaceGet(String),
  NamespaceCurrent,
  NamespaceId(Option<String>),
  NamespaceRename(String, String),
  SwapDb(u64, u64),
  Move(String, u64),
  MoveX {
    key: String,
    target: String,
    replace: bool,
  },
  Slowlog,
  MemoryUsage(String),
  KProfile,
  PerfLog,
  Monitor,
  Shutdown,
  Debug(Vec<String>),
  Disk(Vec<String>),
  Compact,
  Bgsave,
  Lastsave,
  FlushBackup,
  SlaveOf(String, u16),
  ReplicaOf(String, u16),
  Stats,
  Rdb(Vec<String>),
  Reset,
  ApplyBatch(Vec<u8>),
  Dump(String),
  Restore {
    key: String,
    ttl: u64,
    serialized: Vec<u8>,
    replace: bool,
  },
  PollUpdates,
  Sst(Vec<String>),
  FlushMemTable,
  FlushBlockCache,
  Latency(Vec<String>),

  // ================= 2. 字符串 (String) 与位图 (Bit) =================
  Get(String),
  Set {
    key: String,
    value: Vec<u8>,
    ex: Option<u64>,
    px: Option<u64>,
    exat: Option<u64>,
    pxat: Option<u64>,
    nx: bool,
    xx: bool,
    get: bool,
    keepttl: bool,
  },
  SetNx(String, Vec<u8>),
  SetEx(String, u64, Vec<u8>),
  PSetEx(String, u64, Vec<u8>),
  GetSet(String, Vec<u8>),
  GetDel(String),
  GetEx {
    key: String,
    ex: Option<u64>,
    px: Option<u64>,
    persist: bool,
  },
  MGet(Vec<String>),
  MSet(Vec<(String, Vec<u8>)>),
  MSetNx(Vec<(String, Vec<u8>)>),
  MSetEx {
    ttl_sec: u64,
    pairs: Vec<(String, Vec<u8>)>,
  },
  Incr(String),
  Decr(String),
  IncrBy(String, i64),
  DecrBy(String, i64),
  IncrByFloat(String, f64),
  IncrEx {
    key: String,
    by_float: Option<f64>,
    by_int: Option<i64>,
    saturate: bool,
    lbound: Option<f64>,
    ubound: Option<f64>,
    ex: Option<u64>,
    px: Option<u64>,
    exat: Option<u64>,
    pxat: Option<u64>,
    persist: bool,
    enx: bool,
  },
  StrLen(String),
  Append(String, Vec<u8>),
  GetRange(String, i64, i64),
  SetRange(String, usize, Vec<u8>),
  Digest(String),
  DelEx {
    key: String,
    if_eq: Option<Vec<u8>>,
  },
  Cas {
    key: String,
    old_val: Vec<u8>,
    new_val: Vec<u8>,
    ex: Option<u64>,
  },
  Cad {
    key: String,
    val: Vec<u8>,
  },
  Lcs {
    key1: String,
    key2: String,
    len_only: bool,
  },
  GetBit(String, usize),
  SetBit(String, usize, u8),
  BitCount {
    key: String,
    start: Option<i64>,
    end: Option<i64>,
    is_bit: bool,
  },
  BitPos {
    key: String,
    bit: u8,
    start: Option<i64>,
    end: Option<i64>,
  },
  BitOp {
    op: String,
    dest: String,
    src_keys: Vec<String>,
  },
  BitField {
    key: String,
    ops: Vec<wedb_embed::BitfieldOperation>,
  },
  BitFieldRo {
    key: String,
    ops: Vec<wedb_embed::BitfieldOperation>,
  },

  // ================= 3. 通用 Key 管理与过期 =================
  Del(Vec<String>),
  Unlink(Vec<String>),
  Exists(Vec<String>),
  Keys(String),
  Scan {
    cursor: u64,
    pattern: Option<String>,
    count: Option<usize>,
  },
  ScanPrefix {
    prefix: Vec<u8>,
    count: Option<usize>,
  },
  DbSize,
  FlushDb,
  FlushAll,
  Type(String),
  Ttl(String),
  Pttl(String),
  ExpireTime(String),
  PExpireTime(String),
  Expire(String, u64),
  PExpire(String, u64),
  ExpireAt(String, u64),
  PExpireAt(String, u64),
  Persist(String),
  Rename(String, String),
  RenameNx(String, String),
  Copy {
    src: String,
    dst: String,
    db: Option<u32>,
    replace: bool,
  },
  RandomKey,
  Touch(Vec<String>),
  Object {
    subcmd: String,
    key: String,
  },
  Sort {
    key: String,
    by: Option<String>,
    offset: usize,
    count: Option<usize>,
    patterns: Vec<String>,
    desc: bool,
    alpha: bool,
    store: Option<String>,
  },
  SortRo {
    key: String,
    by: Option<String>,
    offset: usize,
    count: Option<usize>,
    patterns: Vec<String>,
    desc: bool,
    alpha: bool,
  },
  KMetaData(String),

  // ================= 4. 哈希表 (Hash) =================
  HSet(String, Vec<(String, Vec<u8>)>),
  HGet(String, String),
  HDel(String, Vec<String>),
  HExists(String, String),
  HLen(String),
  HGetAll(String),
  HKeys(String),
  HVals(String),
  HMGet(String, Vec<String>),
  HMSet(String, Vec<(String, Vec<u8>)>),
  HIncrBy(String, String, i64),
  HIncrByFloat(String, String, f64),
  HSetNx(String, String, Vec<u8>),
  HStrLen(String, String),
  HScan {
    key: String,
    cursor: u64,
    pattern: Option<String>,
    count: Option<usize>,
  },
  HRandField {
    key: String,
    count: Option<i64>,
    with_values: bool,
  },
  HExpire {
    key: String,
    seconds: i64,
    condition: ExpireCondition,
    fields: Vec<String>,
  },
  HPExpire {
    key: String,
    millis: i64,
    condition: ExpireCondition,
    fields: Vec<String>,
  },
  HExpireAt {
    key: String,
    unix_time_sec: i64,
    condition: ExpireCondition,
    fields: Vec<String>,
  },
  HPExpireAt {
    key: String,
    unix_time_ms: i64,
    condition: ExpireCondition,
    fields: Vec<String>,
  },
  HTtl {
    key: String,
    fields: Vec<String>,
  },
  HPTtl {
    key: String,
    fields: Vec<String>,
  },
  HExpireTime {
    key: String,
    fields: Vec<String>,
  },
  HPExpireTime {
    key: String,
    fields: Vec<String>,
  },
  HPersist {
    key: String,
    fields: Vec<String>,
  },
  HSetExpire {
    key: String,
    ttl_sec: u64,
    fields: Vec<String>,
  },
  HGetEx {
    key: String,
    field: String,
  },
  HRangeByLex {
    key: String,
    min: String,
    max: String,
    offset: usize,
    count: Option<usize>,
  },
  HGetDel {
    key: String,
    fields: Vec<String>,
  },

  // ================= 5. 列表 (List) =================
  LPush(String, Vec<Vec<u8>>),
  RPush(String, Vec<Vec<u8>>),
  LPushX(String, Vec<Vec<u8>>),
  RPushX(String, Vec<Vec<u8>>),
  LPop(String, Option<usize>),
  RPop(String, Option<usize>),
  LLen(String),
  LIndex(String, i64),
  LSet(String, i64, Vec<u8>),
  LRange(String, i64, i64),
  LTrim(String, i64, i64),
  LRem(String, i64, Vec<u8>),
  LInsert {
    key: String,
    before: bool,
    pivot: Vec<u8>,
    element: Vec<u8>,
  },
  LMove {
    src: String,
    dst: String,
    src_left: bool,
    dst_left: bool,
  },
  LMoveM {
    src: String,
    dst: String,
    src_left: bool,
    dst_left: bool,
    count: Option<usize>,
    exactly: Option<usize>,
  },
  RPopLPush(String, String),
  LPos {
    key: String,
    element: Vec<u8>,
    rank: Option<i64>,
    count: Option<usize>,
    max_len: Option<usize>,
  },
  BLPop(Vec<String>, f64),
  BRPop(Vec<String>, f64),
  BLMove {
    src: String,
    dst: String,
    src_left: bool,
    dst_left: bool,
    timeout: f64,
  },
  BLMoveM {
    src: String,
    dst: String,
    src_left: bool,
    dst_left: bool,
    count: Option<usize>,
    exactly: Option<usize>,
    timeout: f64,
  },
  LMPop {
    keys: Vec<String>,
    left: bool,
    count: usize,
  },
  BLMPop {
    timeout: f64,
    keys: Vec<String>,
    left: bool,
    count: usize,
  },

  // ================= 6. 集合 (Set) =================
  SAdd(String, Vec<Vec<u8>>),
  SRem(String, Vec<Vec<u8>>),
  SMembers(String),
  SIsMember(String, Vec<u8>),
  SMIsMember(String, Vec<Vec<u8>>),
  SCard(String),
  SPop(String, Option<usize>),
  SRandMember(String, Option<i64>),
  SMove {
    src: String,
    dst: String,
    member: Vec<u8>,
  },
  SUnion(Vec<String>),
  SInter(Vec<String>),
  SDiff(Vec<String>),
  SInterCard {
    keys: Vec<String>,
    limit: usize,
  },
  SDiffCard {
    keys: Vec<String>,
    limit: usize,
  },
  SUnionCard {
    keys: Vec<String>,
    limit: usize,
  },
  SDiffStore(String, Vec<String>),
  SUnionStore(String, Vec<String>),
  SInterStore(String, Vec<String>),
  SScan {
    key: String,
    cursor: u64,
    pattern: Option<String>,
    count: Option<usize>,
  },

  // ================= 7. 有序集合 (Sorted Set / ZSet) =================
  ZAdd {
    key: String,
    nx: bool,
    xx: bool,
    gt: bool,
    lt: bool,
    ch: bool,
    incr: bool,
    members: Vec<(f64, Vec<u8>)>,
  },
  ZRem(String, Vec<Vec<u8>>),
  ZScore(String, Vec<u8>),
  ZMScore(String, Vec<Vec<u8>>),
  ZIncrBy(String, f64, Vec<u8>),
  ZCard(String),
  ZCount(String, String, String),
  ZRange {
    key: String,
    min: String,
    max: String,
    by_score: bool,
    by_lex: bool,
    rev: bool,
    offset: usize,
    count: Option<usize>,
    with_scores: bool,
  },
  ZRevRange(String, i64, i64, bool),
  ZRangeByScore {
    key: String,
    min: String,
    max: String,
    with_scores: bool,
    offset: usize,
    count: Option<usize>,
  },
  ZRank {
    key: String,
    member: Vec<u8>,
    with_score: bool,
  },
  ZRevRank {
    key: String,
    member: Vec<u8>,
    with_score: bool,
  },
  ZScan {
    key: String,
    cursor: u64,
    pattern: Option<String>,
    count: Option<usize>,
  },
  ZPopMin(String, Option<usize>),
  ZPopMax(String, Option<usize>),
  BZPopMin(Vec<String>, f64),
  BZPopMax(Vec<String>, f64),
  ZMPop {
    keys: Vec<String>,
    min: bool,
    count: usize,
  },
  BZMPop {
    timeout: f64,
    keys: Vec<String>,
    min: bool,
    count: usize,
  },
  ZInterStore {
    dst: String,
    keys: Vec<String>,
    weights: Vec<f64>,
    aggregate: String,
  },
  ZInter {
    keys: Vec<String>,
    weights: Vec<f64>,
    aggregate: String,
    with_scores: bool,
  },
  ZInterCard {
    keys: Vec<String>,
    limit: usize,
  },
  ZUnionStore {
    dst: String,
    keys: Vec<String>,
    weights: Vec<f64>,
    aggregate: String,
  },
  ZUnion {
    keys: Vec<String>,
    weights: Vec<f64>,
    aggregate: String,
    with_scores: bool,
  },
  ZDiff {
    keys: Vec<String>,
    with_scores: bool,
  },
  ZDiffStore {
    dst: String,
    keys: Vec<String>,
  },
  ZLexCount(String, String, String),
  ZRangeByLex {
    key: String,
    min: String,
    max: String,
    offset: usize,
    count: Option<usize>,
  },
  ZRevRangeByLex {
    key: String,
    max: String,
    min: String,
    offset: usize,
    count: Option<usize>,
  },
  ZRemRangeByRank(String, i64, i64),
  ZRemRangeByScore(String, String, String),
  ZRemRangeByLex(String, String, String),
  ZRevRangeByScore {
    key: String,
    max: String,
    min: String,
    with_scores: bool,
    offset: usize,
    count: Option<usize>,
  },
  ZRandMember {
    key: String,
    count: Option<i64>,
    with_scores: bool,
  },
  ZRangeStore {
    dst: String,
    src: String,
    min: String,
    max: String,
    by_score: bool,
    by_lex: bool,
    rev: bool,
    offset: usize,
    count: Option<usize>,
  },

  // ================= 8. 基数统计 (HyperLogLog) =================
  PfAdd(String, Vec<Vec<u8>>),
  PfCount(Vec<String>),
  PfMerge(String, Vec<String>),
  PfSelfTest,

  // ================= 9. 布隆与布谷鸟过滤器 (Bloom / Cuckoo) =================
  BfReserve {
    key: String,
    error_rate: f64,
    capacity: u32,
    expansion: u16,
    nonscaling: bool,
  },
  BfAdd(String, Vec<u8>),
  BfMAdd(String, Vec<Vec<u8>>),
  BfInsert {
    key: String,
    capacity: Option<u32>,
    error_rate: Option<f64>,
    expansion: Option<u16>,
    nocreate: bool,
    nonscaling: bool,
    items: Vec<Vec<u8>>,
  },
  BfExists(String, Vec<u8>),
  BfMExists(String, Vec<Vec<u8>>),
  BfInfo {
    key: String,
    sub_cmd: Option<String>,
  },
  BfCard(String),
  CfReserve {
    key: String,
    capacity: u64,
    bucket_size: Option<u8>,
    max_iterations: Option<u16>,
    expansion: Option<u16>,
  },
  CfAdd(String, Vec<u8>),
  CfAddNx(String, Vec<u8>),
  CfInsert {
    key: String,
    capacity: Option<u64>,
    nocreate: bool,
    items: Vec<Vec<u8>>,
  },
  CfInsertNx {
    key: String,
    capacity: Option<u64>,
    nocreate: bool,
    items: Vec<Vec<u8>>,
  },
  CfExists(String, Vec<u8>),
  CfMExists(String, Vec<Vec<u8>>),
  CfDel(String, Vec<u8>),
  CfCount(String, Vec<u8>),
  CfInfo(String),

  // ================= 10. 有序整型集合 (SortedInt) =================
  SiAdd(String, Vec<u64>),
  SiRem(String, Vec<u64>),
  SiCard(String),
  SiExists(String, Vec<u64>),
  SiRange {
    key: String,
    cursor: u64,
    offset: usize,
    limit: usize,
  },
  SiRevRange {
    key: String,
    cursor: u64,
    offset: usize,
    limit: usize,
  },
  SiRangeByValue {
    key: String,
    spec: SortedIntRangeSpec,
  },
  SiRevRangeByValue {
    key: String,
    spec: SortedIntRangeSpec,
  },

  // ================= 11. 空间地理位置 (Geo) =================
  GeoAdd {
    key: String,
    nx: bool,
    xx: bool,
    ch: bool,
    items: Vec<(f64, f64, String)>, // (lon, lat, member)
  },
  GeoDist {
    key: String,
    m1: String,
    m2: String,
    unit: String,
  },
  GeoHash(String, Vec<String>),
  GeoPos(String, Vec<String>),
  GeoRadius {
    key: String,
    lon: f64,
    lat: f64,
    radius: f64,
    unit: String,
    with_coord: bool,
    with_dist: bool,
    with_hash: bool,
    count: Option<usize>,
    any: bool,
    sort_asc: bool,
    sort_desc: bool,
    store: Option<String>,
    store_dist: Option<String>,
  },
  GeoRadiusByMember {
    key: String,
    member: String,
    radius: f64,
    unit: String,
    with_coord: bool,
    with_dist: bool,
    with_hash: bool,
    count: Option<usize>,
    any: bool,
    sort_asc: bool,
    sort_desc: bool,
    store: Option<String>,
    store_dist: Option<String>,
  },
  GeoSearch {
    key: String,
    from_lon_lat: Option<(f64, f64)>,
    from_member: Option<String>,
    by_radius: Option<(f64, String)>,
    by_box: Option<(f64, f64, String)>,
    sort_asc: bool,
    sort_desc: bool,
    count: Option<usize>,
    any: bool,
    with_coord: bool,
    with_dist: bool,
    with_hash: bool,
  },
  GeoSearchStore {
    dst: String,
    src: String,
    from_lon_lat: Option<(f64, f64)>,
    from_member: Option<String>,
    by_radius: Option<(f64, String)>,
    by_box: Option<(f64, f64, String)>,
    sort_asc: bool,
    sort_desc: bool,
    count: Option<usize>,
    any: bool,
    store_dist: bool,
  },

  // ================= 12. 流数据 (Stream) =================
  XAdd {
    key: String,
    id: String,
    fields: Vec<(String, Vec<u8>)>,
    nomkstream: bool,
    max_len: Option<usize>,
    min_id: Option<String>,
    limit: Option<usize>,
    approximate: bool,
  },
  XLen(String),
  XRange {
    key: String,
    start: String,
    end: String,
    count: Option<usize>,
  },
  XRevRange {
    key: String,
    end: String,
    start: String,
    count: Option<usize>,
  },
  XDel(String, Vec<String>),
  XTrim {
    key: String,
    max_len: Option<usize>,
    min_id: Option<String>,
    limit: Option<usize>,
    approximate: bool,
  },
  XRead {
    streams: Vec<String>,
    ids: Vec<String>,
    count: Option<usize>,
    block: Option<u64>,
  },
  XInfo(String, String),
  XInfoStream {
    key: String,
    full: bool,
    count: Option<usize>,
  },
  XAck(String, String, Vec<String>),
  XClaim {
    key: String,
    group: String,
    consumer: String,
    min_idle: u64,
    ids: Vec<String>,
    idle: Option<u64>,
    time: Option<u64>,
    retrycount: Option<u64>,
    force: bool,
    justid: bool,
  },
  XAutoClaim {
    key: String,
    group: String,
    consumer: String,
    min_idle: u64,
    start: String,
    count: Option<usize>,
    justid: bool,
  },
  XGroup(Vec<String>),
  XPending {
    key: String,
    group: String,
    start: Option<String>,
    end: Option<String>,
    count: Option<usize>,
    consumer: Option<String>,
    idle: Option<u64>,
  },
  XReadGroup {
    group: String,
    consumer: String,
    streams: Vec<String>,
    ids: Vec<String>,
    count: Option<usize>,
    block: Option<u64>,
    noack: bool,
  },
  XSetId {
    key: String,
    last_id: String,
    entries_added: Option<u64>,
    max_deleted_id: Option<String>,
  },
  XAckDel {
    key: String,
    group: String,
    ids: Vec<String>,
  },
  XNack {
    key: String,
    group: String,
    ids: Vec<String>,
  },
  XDelEx {
    key: String,
    ids: Vec<String>,
  },

  // ================= 13. JSON 文档 (RedisJSON) =================
  JsonSet {
    key: String,
    path: String,
    value: String,
    nx: bool,
    xx: bool,
  },
  JsonGet {
    key: String,
    indent: Option<String>,
    newline: Option<String>,
    space: Option<String>,
    paths: Vec<String>,
  },
  JsonDel {
    key: String,
    path: Option<String>,
  },
  JsonType {
    key: String,
    path: Option<String>,
  },
  JsonArrAppend {
    key: String,
    path: Option<String>,
    values: Vec<String>,
  },
  JsonArrInsert {
    key: String,
    path: String,
    index: i64,
    values: Vec<String>,
  },
  JsonArrTrim {
    key: String,
    path: String,
    start: i64,
    stop: i64,
  },
  JsonClear {
    key: String,
    path: Option<String>,
  },
  JsonToggle {
    key: String,
    path: Option<String>,
  },
  JsonArrLen {
    key: String,
    path: Option<String>,
  },
  JsonMerge {
    key: String,
    path: String,
    value: String,
  },
  JsonObjKeys {
    key: String,
    path: Option<String>,
  },
  JsonArrPop {
    key: String,
    path: Option<String>,
    index: Option<i64>,
  },
  JsonArrIndex {
    key: String,
    path: String,
    value: String,
  },
  JsonNumIncrBy {
    key: String,
    path: String,
    number: f64,
  },
  JsonNumMultBy {
    key: String,
    path: String,
    number: f64,
  },
  JsonObjLen {
    key: String,
    path: Option<String>,
  },
  JsonStrAppend {
    key: String,
    path: Option<String>,
    value: String,
  },
  JsonStrLen {
    key: String,
    path: Option<String>,
  },
  JsonMGet {
    keys: Vec<String>,
    path: String,
  },
  JsonMSet(Vec<(String, String, String)>),
  JsonDebug(String, Option<String>),
  JsonResp {
    key: String,
    path: Option<String>,
  },
  JsonInfo(String),

  // ================= 14. TDigest 分位数估计 =================
  TDigestCreate {
    key: String,
    compression: Option<f64>,
  },
  TDigestInfo(String),
  TDigestAdd(String, Vec<f64>),
  TDigestMax(String),
  TDigestMin(String),
  TDigestRevRank(String, Vec<f64>),
  TDigestRank(String, Vec<f64>),
  TDigestByRevRank(String, Vec<u64>),
  TDigestByRank(String, Vec<u64>),
  TDigestQuantile(String, Vec<f64>),
  TDigestTrimmedMean(String, f64, f64),
  TDigestReset(String),
  TDigestMerge {
    dst: String,
    sources: Vec<String>,
    compression: Option<f64>,
    override_flag: bool,
  },
  TDigestCdf(String, Vec<f64>),

  // ================= 15. 时间序列 (TimeSeries) =================
  TsCreate {
    key: String,
    retention_ms: u64,
    chunk_size: u64,
    duplicate_policy: Option<String>,
    labels: Vec<(String, String)>,
  },
  TsAlter {
    key: String,
    retention_ms: Option<u64>,
    chunk_size: Option<u64>,
    duplicate_policy: Option<String>,
    labels: Vec<(String, String)>,
  },
  TsAdd {
    key: String,
    timestamp: Option<u64>,
    value: f64,
    retention_ms: Option<u64>,
    chunk_size: Option<u64>,
    on_duplicate: Option<String>,
    labels: Vec<(String, String)>,
  },
  TsMAdd(Vec<(String, Option<u64>, f64)>),
  TsRange {
    key: String,
    from_ts: u64,
    to_ts: u64,
    filter_by_ts: Vec<u64>,
    filter_by_value: Option<(f64, f64)>,
    count: Option<usize>,
    aggregation: Option<(String, u64)>,
    align: Option<u64>,
  },
  TsRevRange {
    key: String,
    from_ts: u64,
    to_ts: u64,
    filter_by_ts: Vec<u64>,
    filter_by_value: Option<(f64, f64)>,
    count: Option<usize>,
    aggregation: Option<(String, u64)>,
    align: Option<u64>,
  },
  TsInfo(String),
  TsGet {
    key: String,
    latest: bool,
  },
  TsCreateRule(String, String, String, u64),
  TsMGet {
    with_labels: bool,
    selected_labels: Vec<String>,
    filters: Vec<String>,
  },
  TsMRange {
    from_ts: u64,
    to_ts: u64,
    filter_by_ts: Vec<u64>,
    filter_by_value: Option<(f64, f64)>,
    count: Option<usize>,
    aggregation: Option<(String, u64)>,
    align: Option<u64>,
    with_labels: bool,
    selected_labels: Vec<String>,
    filters: Vec<String>,
  },
  TsMRevRange {
    from_ts: u64,
    to_ts: u64,
    filter_by_ts: Vec<u64>,
    filter_by_value: Option<(f64, f64)>,
    count: Option<usize>,
    aggregation: Option<(String, u64)>,
    align: Option<u64>,
    with_labels: bool,
    selected_labels: Vec<String>,
    filters: Vec<String>,
  },
  TsIncrBy {
    key: String,
    value: f64,
    timestamp: Option<u64>,
    retention_ms: Option<u64>,
    chunk_size: Option<u64>,
    labels: Vec<(String, String)>,
  },
  TsDecrBy {
    key: String,
    value: f64,
    timestamp: Option<u64>,
    retention_ms: Option<u64>,
    chunk_size: Option<u64>,
    labels: Vec<(String, String)>,
  },
  TsDel(String, u64, u64),
  TsQueryIndex(Vec<String>),

  // ================= 16. 发布订阅 (PubSub) =================
  Publish(String, Vec<u8>),
  MPublish(Vec<(String, Vec<u8>)>),
  Subscribe(Vec<String>),
  Unsubscribe(Vec<String>),
  PSubscribe(Vec<String>),
  PUnsubscribe(Vec<String>),
  SSubscribe(Vec<String>),
  SUnsubscribe(Vec<String>),
  PubSub(Vec<String>),

  // ================= 17. 事务 (Transaction) =================
  Multi,
  Discard,
  Exec,
  Watch(Vec<String>),
  Unwatch,

  // ================= 18. Lua 脚本与函数 (Script & Function) =================
  Eval {
    script: String,
    keys: Vec<String>,
    args: Vec<Vec<u8>>,
  },
  EvalSha {
    sha: String,
    keys: Vec<String>,
    args: Vec<Vec<u8>>,
  },
  Script(Vec<String>),
  Function(Vec<String>),

  // ================= 19. 全文检索 (RediSearch / FT) =================
  FtCreate {
    index: String,
    on_data_type: String,
    prefixes: Vec<String>,
    fields: Vec<String>,
  },
  FtSearch {
    index: String,
    query: String,
    nocontent: bool,
    return_fields: Option<Vec<String>>,
    offset: usize,
    limit: usize,
    sortby: Option<(String, bool)>,
  },
  FtSearchSql {
    index: String,
    query: String,
  },
  FtExplain {
    index: String,
    query: String,
  },
  FtExplainSql {
    index: String,
    query: String,
  },
  FtInfo(String),
  FtList,
  FtDropIndex {
    index: String,
    drop_docs: bool,
  },
  FtAliasAdd {
    alias: String,
    index: String,
  },
  FtAliasDel {
    alias: String,
  },
  FtTagVals(String, String),

  // ================= 20. 集群与复制管理 (Cluster & Replication) =================
  Cluster(Vec<String>),
  ClusterNodes,
  ClusterInfo,
  ClusterSlots,
  ClusterShards,
  ClusterMembers,
  ClusterMyId,
  ClusterKeySlot(String),
  ClusterRebalance,
  ClusterFailover,
  ClusterSaveConfig,
  ClusterReset(bool),
  ClusterCountKeysInSlot(u32),
  ClusterGetKeysInSlot {
    slot: u32,
    count: usize,
  },
  ClusterSetTags {
    node_id: u64,
    tags: Vec<String>,
  },
  ClusterGetTags(u64),
  ClusterMeet {
    ip: String,
    port: u16,
    node_id: Option<u64>,
  },
  ClusterForget(u64),
  ClusterX(Vec<String>),
  ReadOnly,
  ReadWrite,
  Asking,
  ReplConf(Vec<String>),
  PSync(Vec<String>),
  FetchMeta(Vec<String>),
  FetchFile(Vec<String>),
  DbName,
  Wait(i64, i64),

  // ================= 21. OpenRaft 分布式扩展与原子批处理 =================
  RaftJoin {
    node_id: u64,
    endpoint: String,
  },
  RaftLeave(u64),
  RaftMembers,
  RaftSnapshot,
  RaftSnapshotStatus,
  RaftPurge(u64),
  RaftHealth,
  RaftMetrics,
  RaftStatus,
  Batch(Vec<BatchOp>),
  Txn(TxnReq),
}
