[package]
name = "wcluster"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitcode = "0.6.9"
compio = { version = "0.19.2", features = ["runtime", "time"] }
gxhash = "3.5.0"
log = "0.4.34"
parking_lot = "0.12.5"
strum = { version = "0.28.0", features = ["derive"] }
thiserror.workspace = true
uuid = { version = "1.26.0", features = ["v4"] }
wedb_standalone = { version = "0.1.0", path = "../../node/wedb_standalone" }

[dev-dependencies]
aok = "0.1.18"
