[package]
name = "wresources"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/wresources"
description = "Embedded command resources (garnet libs/resources)"
keywords = ["resp", "redis", "resources", "metadata"]
categories = ["encoding"]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
