[package]
name = "wdatabase"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/wdatabase"
description = "Garnet logical database and multi-database management"

[lints]
workspace = true

[dependencies]
async-lock.workspace = true
coarsetime.workspace = true
gxhash.workspace = true
log.workspace = true
parking_lot.workspace = true
waof.workspace = true
wbase = { version = "0.1.6", path = "../wbase", features = ["map"] }
wcpr.workspace = true
wdev.workspace = true
whasher.workspace = true
wkv.workspace = true
wtxn = { version = "0.1.0", path = "../wtxn" }
wval.workspace = true

[dev-dependencies]
aok.workspace = true
compio = { workspace = true, features = ["runtime"] }
ctor.workspace = true
log_init.workspace = true
tempfile.workspace = true
