[package]
name = "wraft"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Pure Raft-style consensus library: leader election state machine and pluggable consensus engine interface (zero IO, zero engine dependency)"

[dependencies]
gxhash = "3.5.0"
thiserror = { workspace = true }

[dev-dependencies]
aok = "0.1.18"
compio = "0.19.2"
