[package]
name = "wcustom"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/wcustom"
description = "Custom commands and extensions registry for wedb"

[dependencies]
gxhash.workspace = true
parking_lot.workspace = true
wresp.workspace = true
wtxn.workspace = true
wval.workspace = true

[lints]
workspace = true
