[package]
name = "wcol"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/wcol"
description = "wcol"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
wbftree = { workspace = true }
wbase = { workspace = true, features = ["float"] }
thiserror.workspace = true

[dev-dependencies]
aok.workspace = true
ctor.workspace = true
fastrand.workspace = true
log.workspace = true
log_init.workspace = true
tempfile.workspace = true
