[package]
name = "wserver"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/wserver"
description = "wserver"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitflags = "2.13.1"
coarsetime.workspace = true
num_enum = "0.7.6"
parking_lot.workspace = true
thiserror = "2.0.20"
wbase.workspace = true
wdev.workspace = true
wepoch.workspace = true
whasher.workspace = true
whlog.workspace = true
wkv = { version = "0.1.0", path = "../wkv" }
wobject = { version = "0.1.0", path = "../wobject" }
wresp = { version = "0.1.0", path = "../wresp" }
wval.workspace = true

[dev-dependencies]
aok = "0.1.18"
ctor = "1.0.13"
log = "0.4.34"
log_init = "0.1.39"

[lints]
workspace = true
