[package]
name = "wedb"
description = "WeDB 集群层：选主、共识、AOF 同步驱动与范围索引文件流迁移（对标 Garnet libs/cluster）"

[package.version]
workspace = true

[package.edition]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true

[dependencies.wedb_standalone]
workspace = true

[dependencies.wraft]
workspace = true

[dependencies.thiserror]
workspace = true

[dev-dependencies]
aok = "0.1.18"
compio = "0.19.2"
parking_lot = "0.12.5"
tempfile = "3"

[dev-dependencies.wdev]
path = "../../embed/wdev"
version = "0.1.2"
