[workspace]
resolver = "3"
members = ["wraft", "wedb", "wcluster"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = ""

[workspace.dependencies]
wraft = { version = "0.1.0", path = "wraft" }
wedb_standalone = { path = "../node/wedb_standalone" }
thiserror = "2.0.20"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
