//! 集成测试子模块聚合（由 main.rs 以 `mod suite;` 挂载，避免各文件被 Cargo 识别为独立测试二进制）
#[cfg(feature = "addr")]
pub mod addr;
#[cfg(feature = "pool")]
pub mod align;
#[cfg(feature = "pool")]
pub mod aligned_buf;
pub mod ascii;
#[cfg(feature = "backoff")]
pub mod backoff;
#[cfg(feature = "base32")]
pub mod base32;
#[cfg(feature = "convert")]
pub mod convert;
#[cfg(feature = "crc")]
pub mod crc;
#[cfg(feature = "crc64")]
pub mod crc64;
#[cfg(feature = "endpoint")]
pub mod endpoint;
#[cfg(feature = "future")]
pub mod future;
#[cfg(feature = "glob")]
pub mod glob;
#[cfg(feature = "group-commit")]
pub mod group_commit;
#[cfg(feature = "hash")]
pub mod hash;
#[cfg(feature = "hash_slot")]
pub mod hash_slot;
#[cfg(feature = "hex")]
pub mod hex;
pub mod keyfmt;
pub mod ns_prefix;
#[cfg(feature = "num")]
pub mod num;
#[cfg(feature = "pool")]
pub mod pool_budget;
#[cfg(feature = "pool")]
pub mod pool_cross_thread;
#[cfg(feature = "pool")]
pub mod pool_get_return;
#[cfg(feature = "pool")]
pub mod pool_ladder;
#[cfg(feature = "pool")]
pub mod pool_limited;
#[cfg(feature = "pool")]
pub mod pool_stress;
#[cfg(feature = "primed")]
pub mod primed;
#[cfg(feature = "simd")]
pub mod simd;
#[cfg(feature = "store_type")]
pub mod store_type;
#[cfg(feature = "striped")]
pub mod striped;
#[cfg(feature = "supervise")]
pub mod supervise;
#[cfg(feature = "thread")]
pub mod thread;
#[cfg(feature = "time")]
pub mod time;
#[cfg(feature = "varint")]
pub mod varint;
