[package]
name = "ext_json"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/ext_json"
description = "RedisJSON extension: JSON commands, JSONPath queries, and object integration"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
jsonpath-rust = "1.0.10"
serde_json = "1.0.151"
sonic-rs.workspace = true
thiserror = "2.0.20"

[dev-dependencies]
aok = "0.1.18"
ctor = "1.0.13"
log = "0.4.34"
log_init = "0.1.39"

[lints]
workspace = true
