[package]
name = "wcpr"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb_base.git"
homepage = "https://github.com/webc-site/wedb_base/tree/main/wcpr"
description = "wcpr"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitcode = { workspace = true }
wbase = { workspace = true, features = ["crc", "time"] }
itoa = { workspace = true }
log = { workspace = true }
sonic-rs = { workspace = true }
thiserror = { workspace = true }
wdev = { workspace = true }
wepoch = { workspace = true }
whlog = { workspace = true }
windex = { workspace = true }

[dependencies.compio]
workspace = true
features = ["fs", "runtime", "time"]

[dependencies.serde]
workspace = true
features = ["derive"]

[dev-dependencies]
aok = { workspace = true }
ctor = { workspace = true }
log = { workspace = true }
log_init = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
