//! ACL 命令目录静态数据（自 garnet/libs/resources/RespCommandsInfo.json 生成，
//! 覆盖全部根命令与子命令的名称 / ACL 分类 / 父子关系）

use wresp::RespCommand;

use super::RespAclCategories;

/// 单条命令目录（RespCommandsInfo 中 ACL 消费的最小面）
pub struct CmdEntry {
  /// C# 枚举成员名（Enum.TryParse 对照，含下划线）
  pub cs: &'static str,
  /// 展示名（info.Name 小写；子命令为 parent|sub 形式）
  pub name: &'static str,
  /// 对应 RespCommand
  pub cmd: RespCommand,
  /// ACL 分类位集
  pub cats: RespAclCategories,
  /// 父命令（仅子命令有）
  pub parent: Option<RespCommand>,
}

/// 全量命令目录（根 + 子命令扁平表，序即 JSON 声明序）
pub static CMD_ENTRIES: &[CmdEntry] = &[
  CmdEntry {
    cs: "ACL",
    name: "acl",
    cmd: RespCommand::Acl,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "ACL_CAT",
    name: "acl|cat",
    cmd: RespCommand::AclCat,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "ACL_DELUSER",
    name: "acl|deluser",
    cmd: RespCommand::AclDeluser,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "ACL_GENPASS",
    name: "acl|genpass",
    cmd: RespCommand::AclGenpass,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "ACL_GETUSER",
    name: "acl|getuser",
    cmd: RespCommand::AclGetuser,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "ACL_LIST",
    name: "acl|list",
    cmd: RespCommand::AclList,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "ACL_LOAD",
    name: "acl|load",
    cmd: RespCommand::AclLoad,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "ACL_SAVE",
    name: "acl|save",
    cmd: RespCommand::AclSave,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "ACL_SETUSER",
    name: "acl|setuser",
    cmd: RespCommand::AclSetuser,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "ACL_USERS",
    name: "acl|users",
    cmd: RespCommand::AclUsers,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "ACL_WHOAMI",
    name: "acl|whoami",
    cmd: RespCommand::AclWhoami,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Acl),
  },
  CmdEntry {
    cs: "APPEND",
    name: "append",
    cmd: RespCommand::Append,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "ASKING",
    name: "asking",
    cmd: RespCommand::Asking,
    cats: RespAclCategories::from_bits_retain(0x108),
    parent: None,
  },
  CmdEntry {
    cs: "ASYNC",
    name: "async",
    cmd: RespCommand::Async,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "AUTH",
    name: "auth",
    cmd: RespCommand::Auth,
    cats: RespAclCategories::from_bits_retain(0x108),
    parent: None,
  },
  CmdEntry {
    cs: "BGSAVE",
    name: "bgsave",
    cmd: RespCommand::Bgsave,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: None,
  },
  CmdEntry {
    cs: "BITCOUNT",
    name: "bitcount",
    cmd: RespCommand::Bitcount,
    cats: RespAclCategories::from_bits_retain(0x11002),
    parent: None,
  },
  CmdEntry {
    cs: "BITFIELD",
    name: "bitfield",
    cmd: RespCommand::Bitfield,
    cats: RespAclCategories::from_bits_retain(0x110002),
    parent: None,
  },
  CmdEntry {
    cs: "BITFIELD_RO",
    name: "bitfield_ro",
    cmd: RespCommand::BitfieldRo,
    cats: RespAclCategories::from_bits_retain(0x1102),
    parent: None,
  },
  CmdEntry {
    cs: "BITOP",
    name: "bitop",
    cmd: RespCommand::Bitop,
    cats: RespAclCategories::from_bits_retain(0x110002),
    parent: None,
  },
  CmdEntry {
    cs: "BITPOS",
    name: "bitpos",
    cmd: RespCommand::Bitpos,
    cats: RespAclCategories::from_bits_retain(0x11002),
    parent: None,
  },
  CmdEntry {
    cs: "BLMOVE",
    name: "blmove",
    cmd: RespCommand::Blmove,
    cats: RespAclCategories::from_bits_retain(0x110404),
    parent: None,
  },
  CmdEntry {
    cs: "BLMPOP",
    name: "blmpop",
    cmd: RespCommand::Blmpop,
    cats: RespAclCategories::from_bits_retain(0x110404),
    parent: None,
  },
  CmdEntry {
    cs: "BLPOP",
    name: "blpop",
    cmd: RespCommand::Blpop,
    cats: RespAclCategories::from_bits_retain(0x110404),
    parent: None,
  },
  CmdEntry {
    cs: "BRPOP",
    name: "brpop",
    cmd: RespCommand::Brpop,
    cats: RespAclCategories::from_bits_retain(0x110404),
    parent: None,
  },
  CmdEntry {
    cs: "BRPOPLPUSH",
    name: "brpoplpush",
    cmd: RespCommand::Brpoplpush,
    cats: RespAclCategories::from_bits_retain(0x110404),
    parent: None,
  },
  CmdEntry {
    cs: "BZMPOP",
    name: "bzmpop",
    cmd: RespCommand::Bzmpop,
    cats: RespAclCategories::from_bits_retain(0x118004),
    parent: None,
  },
  CmdEntry {
    cs: "BZPOPMAX",
    name: "bzpopmax",
    cmd: RespCommand::Bzpopmax,
    cats: RespAclCategories::from_bits_retain(0x108104),
    parent: None,
  },
  CmdEntry {
    cs: "BZPOPMIN",
    name: "bzpopmin",
    cmd: RespCommand::Bzpopmin,
    cats: RespAclCategories::from_bits_retain(0x108104),
    parent: None,
  },
  CmdEntry {
    cs: "CLIENT",
    name: "client",
    cmd: RespCommand::Client,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "CLIENT_GETNAME",
    name: "client|getname",
    cmd: RespCommand::ClientGetname,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Client),
  },
  CmdEntry {
    cs: "CLIENT_ID",
    name: "client|id",
    cmd: RespCommand::ClientId,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Client),
  },
  CmdEntry {
    cs: "CLIENT_INFO",
    name: "client|info",
    cmd: RespCommand::ClientInfo,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Client),
  },
  CmdEntry {
    cs: "CLIENT_KILL",
    name: "client|kill",
    cmd: RespCommand::ClientKill,
    cats: RespAclCategories::from_bits_retain(0x10019),
    parent: Some(RespCommand::Client),
  },
  CmdEntry {
    cs: "CLIENT_LIST",
    name: "client|list",
    cmd: RespCommand::ClientList,
    cats: RespAclCategories::from_bits_retain(0x10019),
    parent: Some(RespCommand::Client),
  },
  CmdEntry {
    cs: "CLIENT_SETINFO",
    name: "client|setinfo",
    cmd: RespCommand::ClientSetinfo,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Client),
  },
  CmdEntry {
    cs: "CLIENT_SETNAME",
    name: "client|setname",
    cmd: RespCommand::ClientSetname,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Client),
  },
  CmdEntry {
    cs: "CLIENT_UNBLOCK",
    name: "client|unblock",
    cmd: RespCommand::ClientUnblock,
    cats: RespAclCategories::from_bits_retain(0x10019),
    parent: Some(RespCommand::Client),
  },
  CmdEntry {
    cs: "CLUSTER",
    name: "cluster",
    cmd: RespCommand::Cluster,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "CLUSTER_ADDSLOTS",
    name: "cluster|addslots",
    cmd: RespCommand::ClusterAddslots,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_ADDSLOTSRANGE",
    name: "cluster|addslotsrange",
    cmd: RespCommand::ClusterAddslotsrange,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_ADVANCE_TIME",
    name: "cluster|advance_time",
    cmd: RespCommand::ClusterAdvanceTime,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_APPENDLOG",
    name: "cluster|appendlog",
    cmd: RespCommand::ClusterAppendlog,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_ATTACH_SYNC",
    name: "cluster|attach_sync",
    cmd: RespCommand::ClusterAttachSync,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_BANLIST",
    name: "cluster|banlist",
    cmd: RespCommand::ClusterBanlist,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_BEGIN_REPLICA_RECOVER",
    name: "cluster|begin_replica_recover",
    cmd: RespCommand::ClusterBeginReplicaRecover,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_BUMPEPOCH",
    name: "cluster|bumpepoch",
    cmd: RespCommand::ClusterBumpepoch,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_COUNTKEYSINSLOT",
    name: "cluster|countkeysinslot",
    cmd: RespCommand::ClusterCountkeysinslot,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_DELKEYSINSLOT",
    name: "cluster|delkeysinslot",
    cmd: RespCommand::ClusterDelkeysinslot,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_DELKEYSINSLOTRANGE",
    name: "cluster|delkeysinslotrange",
    cmd: RespCommand::ClusterDelkeysinslotrange,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_DELSLOTS",
    name: "cluster|delslots",
    cmd: RespCommand::ClusterDelslots,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_DELSLOTSRANGE",
    name: "cluster|delslotsrange",
    cmd: RespCommand::ClusterDelslotsrange,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_ENDPOINT",
    name: "cluster|endpoint",
    cmd: RespCommand::ClusterEndpoint,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_FAILOVER",
    name: "cluster|failover",
    cmd: RespCommand::ClusterFailover,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_FAILREPLICATIONOFFSET",
    name: "cluster|failreplicationoffset",
    cmd: RespCommand::ClusterFailreplicationoffset,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_FAILSTOPWRITES",
    name: "cluster|failstopwrites",
    cmd: RespCommand::ClusterFailstopwrites,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_FLUSHALL",
    name: "cluster|flushall",
    cmd: RespCommand::ClusterFlushall,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_FORGET",
    name: "cluster|forget",
    cmd: RespCommand::ClusterForget,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_GETKEYSINSLOT",
    name: "cluster|getkeysinslot",
    cmd: RespCommand::ClusterGetkeysinslot,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_GOSSIP",
    name: "cluster|gossip",
    cmd: RespCommand::ClusterGossip,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_HELP",
    name: "cluster|help",
    cmd: RespCommand::ClusterHelp,
    cats: RespAclCategories::from_bits_retain(0x210001),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_INFO",
    name: "cluster|info",
    cmd: RespCommand::ClusterInfo,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_INITIATE_REPLICA_SYNC",
    name: "cluster|initiate_replica_sync",
    cmd: RespCommand::ClusterInitiateReplicaSync,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_KEYSLOT",
    name: "cluster|keyslot",
    cmd: RespCommand::ClusterKeyslot,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_MEET",
    name: "cluster|meet",
    cmd: RespCommand::ClusterMeet,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_MIGRATE",
    name: "cluster|migrate",
    cmd: RespCommand::ClusterMigrate,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_MLOG_KEY_TIME",
    name: "cluster|mlog_key_time",
    cmd: RespCommand::ClusterMlogKeyTime,
    cats: RespAclCategories::from_bits_retain(0x210001),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_MTASKS",
    name: "cluster|mtasks",
    cmd: RespCommand::ClusterMtasks,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_MYID",
    name: "cluster|myid",
    cmd: RespCommand::ClusterMyid,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_MYPARENTID",
    name: "cluster|myparentid",
    cmd: RespCommand::ClusterMyparentid,
    cats: RespAclCategories::from_bits_retain(0x200001),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_NODES",
    name: "cluster|nodes",
    cmd: RespCommand::ClusterNodes,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_PUBLISH",
    name: "cluster|publish",
    cmd: RespCommand::ClusterPublish,
    cats: RespAclCategories::from_bits_retain(0x210801),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_REPLICAS",
    name: "cluster|replicas",
    cmd: RespCommand::ClusterReplicas,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_REPLICATE",
    name: "cluster|replicate",
    cmd: RespCommand::ClusterReplicate,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_RESERVE",
    name: "cluster|reserve",
    cmd: RespCommand::ClusterReserve,
    cats: RespAclCategories::from_bits_retain(0x200011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_RESET",
    name: "cluster|reset",
    cmd: RespCommand::ClusterReset,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SEND_CKPT_FILE_SEGMENT",
    name: "cluster|send_ckpt_file_segment",
    cmd: RespCommand::ClusterSendCkptFileSegment,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SEND_CKPT_METADATA",
    name: "cluster|send_ckpt_metadata",
    cmd: RespCommand::ClusterSendCkptMetadata,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SETCONFIGEPOCH",
    name: "cluster|set-config-epoch",
    cmd: RespCommand::ClusterSetconfigepoch,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SETSLOT",
    name: "cluster|setslot",
    cmd: RespCommand::ClusterSetslot,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SETSLOTSRANGE",
    name: "cluster|setslotsrange",
    cmd: RespCommand::ClusterSetslotsrange,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SHARDS",
    name: "cluster|shards",
    cmd: RespCommand::ClusterShards,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SLOTS",
    name: "cluster|slots",
    cmd: RespCommand::ClusterSlots,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SLOTSTATE",
    name: "cluster|slotstate",
    cmd: RespCommand::ClusterSlotstate,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SNAPSHOT_DATA",
    name: "cluster|snapshot_data",
    cmd: RespCommand::ClusterSnapshotData,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SPUBLISH",
    name: "cluster|spublish",
    cmd: RespCommand::ClusterSpublish,
    cats: RespAclCategories::from_bits_retain(0x210801),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "CLUSTER_SYNC",
    name: "cluster|sync",
    cmd: RespCommand::ClusterSync,
    cats: RespAclCategories::from_bits_retain(0x210011),
    parent: Some(RespCommand::Cluster),
  },
  CmdEntry {
    cs: "COMMAND",
    name: "command",
    cmd: RespCommand::Command,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: None,
  },
  CmdEntry {
    cs: "COMMAND_COUNT",
    name: "command|count",
    cmd: RespCommand::CommandCount,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Command),
  },
  CmdEntry {
    cs: "COMMAND_DOCS",
    name: "command|docs",
    cmd: RespCommand::CommandDocs,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Command),
  },
  CmdEntry {
    cs: "COMMAND_GETKEYS",
    name: "command|getkeys",
    cmd: RespCommand::CommandGetkeys,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Command),
  },
  CmdEntry {
    cs: "COMMAND_GETKEYSANDFLAGS",
    name: "command|getkeysandflags",
    cmd: RespCommand::CommandGetkeysandflags,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Command),
  },
  CmdEntry {
    cs: "COMMAND_INFO",
    name: "command|info",
    cmd: RespCommand::CommandInfo,
    cats: RespAclCategories::from_bits_retain(0x10008),
    parent: Some(RespCommand::Command),
  },
  CmdEntry {
    cs: "COMMITAOF",
    name: "commitaof",
    cmd: RespCommand::Commitaof,
    cats: RespAclCategories::from_bits_retain(0x200001),
    parent: None,
  },
  CmdEntry {
    cs: "CONFIG",
    name: "config",
    cmd: RespCommand::Config,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "CONFIG_GET",
    name: "config|get",
    cmd: RespCommand::ConfigGet,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Config),
  },
  CmdEntry {
    cs: "CONFIG_REWRITE",
    name: "config|rewrite",
    cmd: RespCommand::ConfigRewrite,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Config),
  },
  CmdEntry {
    cs: "CONFIG_SET",
    name: "config|set",
    cmd: RespCommand::ConfigSet,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Config),
  },
  CmdEntry {
    cs: "COSCAN",
    name: "coscan",
    cmd: RespCommand::Coscan,
    cats: RespAclCategories::from_bits_retain(0x211000),
    parent: None,
  },
  CmdEntry {
    cs: "CustomObjCmd",
    name: "customobjcmd",
    cmd: RespCommand::Customobjcmd,
    cats: RespAclCategories::from_bits_retain(0x610010),
    parent: None,
  },
  CmdEntry {
    cs: "CustomProcedure",
    name: "customprocedure",
    cmd: RespCommand::Customprocedure,
    cats: RespAclCategories::from_bits_retain(0x610010),
    parent: None,
  },
  CmdEntry {
    cs: "CustomRawStringCmd",
    name: "customrawstringcmd",
    cmd: RespCommand::Customrawstringcmd,
    cats: RespAclCategories::from_bits_retain(0x610010),
    parent: None,
  },
  CmdEntry {
    cs: "CustomTxn",
    name: "customtxn",
    cmd: RespCommand::Customtxn,
    cats: RespAclCategories::from_bits_retain(0x610010),
    parent: None,
  },
  CmdEntry {
    cs: "DBSIZE",
    name: "dbsize",
    cmd: RespCommand::Dbsize,
    cats: RespAclCategories::from_bits_retain(0x1300),
    parent: None,
  },
  CmdEntry {
    cs: "DEBUG",
    name: "debug",
    cmd: RespCommand::Debug,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: None,
  },
  CmdEntry {
    cs: "DECR",
    name: "decr",
    cmd: RespCommand::Decr,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "DECRBY",
    name: "decrby",
    cmd: RespCommand::Decrby,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "DEL",
    name: "del",
    cmd: RespCommand::Del,
    cats: RespAclCategories::from_bits_retain(0x110200),
    parent: None,
  },
  CmdEntry {
    cs: "DELIFGREATER",
    name: "delifgreater",
    cmd: RespCommand::Delifgreater,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "DISCARD",
    name: "discard",
    cmd: RespCommand::Discard,
    cats: RespAclCategories::from_bits_retain(0x80100),
    parent: None,
  },
  CmdEntry {
    cs: "DUMP",
    name: "dump",
    cmd: RespCommand::Dump,
    cats: RespAclCategories::from_bits_retain(0x11200),
    parent: None,
  },
  CmdEntry {
    cs: "ECHO",
    name: "echo",
    cmd: RespCommand::Echo,
    cats: RespAclCategories::from_bits_retain(0x108),
    parent: None,
  },
  CmdEntry {
    cs: "EVAL",
    name: "eval",
    cmd: RespCommand::Eval,
    cats: RespAclCategories::from_bits_retain(0x12000),
    parent: None,
  },
  CmdEntry {
    cs: "EVALSHA",
    name: "evalsha",
    cmd: RespCommand::Evalsha,
    cats: RespAclCategories::from_bits_retain(0x12000),
    parent: None,
  },
  CmdEntry {
    cs: "EXEC",
    name: "exec",
    cmd: RespCommand::Exec,
    cats: RespAclCategories::from_bits_retain(0x90000),
    parent: None,
  },
  CmdEntry {
    cs: "EXISTS",
    name: "exists",
    cmd: RespCommand::Exists,
    cats: RespAclCategories::from_bits_retain(0x1300),
    parent: None,
  },
  CmdEntry {
    cs: "EXPDELSCAN",
    name: "expdelscan",
    cmd: RespCommand::Expdelscan,
    cats: RespAclCategories::from_bits_retain(0x200001),
    parent: None,
  },
  CmdEntry {
    cs: "EXPIRE",
    name: "expire",
    cmd: RespCommand::Expire,
    cats: RespAclCategories::from_bits_retain(0x100300),
    parent: None,
  },
  CmdEntry {
    cs: "EXPIREAT",
    name: "expireat",
    cmd: RespCommand::Expireat,
    cats: RespAclCategories::from_bits_retain(0x100300),
    parent: None,
  },
  CmdEntry {
    cs: "EXPIRETIME",
    name: "expiretime",
    cmd: RespCommand::Expiretime,
    cats: RespAclCategories::from_bits_retain(0x1300),
    parent: None,
  },
  CmdEntry {
    cs: "FAILOVER",
    name: "failover",
    cmd: RespCommand::Failover,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: None,
  },
  CmdEntry {
    cs: "FLUSHALL",
    name: "flushall",
    cmd: RespCommand::Flushall,
    cats: RespAclCategories::from_bits_retain(0x110210),
    parent: None,
  },
  CmdEntry {
    cs: "FLUSHDB",
    name: "flushdb",
    cmd: RespCommand::Flushdb,
    cats: RespAclCategories::from_bits_retain(0x110210),
    parent: None,
  },
  CmdEntry {
    cs: "GEOADD",
    name: "geoadd",
    cmd: RespCommand::Geoadd,
    cats: RespAclCategories::from_bits_retain(0x110020),
    parent: None,
  },
  CmdEntry {
    cs: "GEODIST",
    name: "geodist",
    cmd: RespCommand::Geodist,
    cats: RespAclCategories::from_bits_retain(0x11020),
    parent: None,
  },
  CmdEntry {
    cs: "GEOHASH",
    name: "geohash",
    cmd: RespCommand::Geohash,
    cats: RespAclCategories::from_bits_retain(0x11020),
    parent: None,
  },
  CmdEntry {
    cs: "GEOPOS",
    name: "geopos",
    cmd: RespCommand::Geopos,
    cats: RespAclCategories::from_bits_retain(0x11020),
    parent: None,
  },
  CmdEntry {
    cs: "GEORADIUS",
    name: "georadius",
    cmd: RespCommand::Georadius,
    cats: RespAclCategories::from_bits_retain(0x110020),
    parent: None,
  },
  CmdEntry {
    cs: "GEORADIUS_RO",
    name: "georadius_ro",
    cmd: RespCommand::GeoradiusRo,
    cats: RespAclCategories::from_bits_retain(0x11020),
    parent: None,
  },
  CmdEntry {
    cs: "GEORADIUSBYMEMBER",
    name: "georadiusbymember",
    cmd: RespCommand::Georadiusbymember,
    cats: RespAclCategories::from_bits_retain(0x110020),
    parent: None,
  },
  CmdEntry {
    cs: "GEORADIUSBYMEMBER_RO",
    name: "georadiusbymember_ro",
    cmd: RespCommand::GeoradiusbymemberRo,
    cats: RespAclCategories::from_bits_retain(0x11020),
    parent: None,
  },
  CmdEntry {
    cs: "GEOSEARCH",
    name: "geosearch",
    cmd: RespCommand::Geosearch,
    cats: RespAclCategories::from_bits_retain(0x11020),
    parent: None,
  },
  CmdEntry {
    cs: "GEOSEARCHSTORE",
    name: "geosearchstore",
    cmd: RespCommand::Geosearchstore,
    cats: RespAclCategories::from_bits_retain(0x110020),
    parent: None,
  },
  CmdEntry {
    cs: "GET",
    name: "get",
    cmd: RespCommand::Get,
    cats: RespAclCategories::from_bits_retain(0x41100),
    parent: None,
  },
  CmdEntry {
    cs: "GETBIT",
    name: "getbit",
    cmd: RespCommand::Getbit,
    cats: RespAclCategories::from_bits_retain(0x1102),
    parent: None,
  },
  CmdEntry {
    cs: "GETDEL",
    name: "getdel",
    cmd: RespCommand::Getdel,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "GETEX",
    name: "getex",
    cmd: RespCommand::Getex,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "GETIFNOTMATCH",
    name: "getifnotmatch",
    cmd: RespCommand::Getifnotmatch,
    cats: RespAclCategories::from_bits_retain(0x41100),
    parent: None,
  },
  CmdEntry {
    cs: "GETRANGE",
    name: "getrange",
    cmd: RespCommand::Getrange,
    cats: RespAclCategories::from_bits_retain(0x51000),
    parent: None,
  },
  CmdEntry {
    cs: "GETSET",
    name: "getset",
    cmd: RespCommand::Getset,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "GETWITHETAG",
    name: "getwithetag",
    cmd: RespCommand::Getwithetag,
    cats: RespAclCategories::from_bits_retain(0x41100),
    parent: None,
  },
  CmdEntry {
    cs: "HCOLLECT",
    name: "hcollect",
    cmd: RespCommand::Hcollect,
    cats: RespAclCategories::from_bits_retain(0x300041),
    parent: None,
  },
  CmdEntry {
    cs: "HDEL",
    name: "hdel",
    cmd: RespCommand::Hdel,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HELLO",
    name: "hello",
    cmd: RespCommand::Hello,
    cats: RespAclCategories::from_bits_retain(0x108),
    parent: None,
  },
  CmdEntry {
    cs: "HEXISTS",
    name: "hexists",
    cmd: RespCommand::Hexists,
    cats: RespAclCategories::from_bits_retain(0x1140),
    parent: None,
  },
  CmdEntry {
    cs: "HEXPIRE",
    name: "hexpire",
    cmd: RespCommand::Hexpire,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HEXPIREAT",
    name: "hexpireat",
    cmd: RespCommand::Hexpireat,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HEXPIRETIME",
    name: "hexpiretime",
    cmd: RespCommand::Hexpiretime,
    cats: RespAclCategories::from_bits_retain(0x1140),
    parent: None,
  },
  CmdEntry {
    cs: "HGET",
    name: "hget",
    cmd: RespCommand::Hget,
    cats: RespAclCategories::from_bits_retain(0x1140),
    parent: None,
  },
  CmdEntry {
    cs: "HGETALL",
    name: "hgetall",
    cmd: RespCommand::Hgetall,
    cats: RespAclCategories::from_bits_retain(0x11040),
    parent: None,
  },
  CmdEntry {
    cs: "HINCRBY",
    name: "hincrby",
    cmd: RespCommand::Hincrby,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HINCRBYFLOAT",
    name: "hincrbyfloat",
    cmd: RespCommand::Hincrbyfloat,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HKEYS",
    name: "hkeys",
    cmd: RespCommand::Hkeys,
    cats: RespAclCategories::from_bits_retain(0x11040),
    parent: None,
  },
  CmdEntry {
    cs: "HLEN",
    name: "hlen",
    cmd: RespCommand::Hlen,
    cats: RespAclCategories::from_bits_retain(0x1140),
    parent: None,
  },
  CmdEntry {
    cs: "HMGET",
    name: "hmget",
    cmd: RespCommand::Hmget,
    cats: RespAclCategories::from_bits_retain(0x1140),
    parent: None,
  },
  CmdEntry {
    cs: "HMSET",
    name: "hmset",
    cmd: RespCommand::Hmset,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HPERSIST",
    name: "hpersist",
    cmd: RespCommand::Hpersist,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HPEXPIRE",
    name: "hpexpire",
    cmd: RespCommand::Hpexpire,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HPEXPIREAT",
    name: "hpexpireat",
    cmd: RespCommand::Hpexpireat,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HPEXPIRETIME",
    name: "hpexpiretime",
    cmd: RespCommand::Hpexpiretime,
    cats: RespAclCategories::from_bits_retain(0x1140),
    parent: None,
  },
  CmdEntry {
    cs: "HPTTL",
    name: "hpttl",
    cmd: RespCommand::Hpttl,
    cats: RespAclCategories::from_bits_retain(0x1140),
    parent: None,
  },
  CmdEntry {
    cs: "HRANDFIELD",
    name: "hrandfield",
    cmd: RespCommand::Hrandfield,
    cats: RespAclCategories::from_bits_retain(0x11040),
    parent: None,
  },
  CmdEntry {
    cs: "HSCAN",
    name: "hscan",
    cmd: RespCommand::Hscan,
    cats: RespAclCategories::from_bits_retain(0x11040),
    parent: None,
  },
  CmdEntry {
    cs: "HSET",
    name: "hset",
    cmd: RespCommand::Hset,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HSETNX",
    name: "hsetnx",
    cmd: RespCommand::Hsetnx,
    cats: RespAclCategories::from_bits_retain(0x100140),
    parent: None,
  },
  CmdEntry {
    cs: "HSTRLEN",
    name: "hstrlen",
    cmd: RespCommand::Hstrlen,
    cats: RespAclCategories::from_bits_retain(0x1140),
    parent: None,
  },
  CmdEntry {
    cs: "HTTL",
    name: "httl",
    cmd: RespCommand::Httl,
    cats: RespAclCategories::from_bits_retain(0x1140),
    parent: None,
  },
  CmdEntry {
    cs: "HVALS",
    name: "hvals",
    cmd: RespCommand::Hvals,
    cats: RespAclCategories::from_bits_retain(0x11040),
    parent: None,
  },
  CmdEntry {
    cs: "INCR",
    name: "incr",
    cmd: RespCommand::Incr,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "INCRBY",
    name: "incrby",
    cmd: RespCommand::Incrby,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "INCRBYFLOAT",
    name: "incrbyfloat",
    cmd: RespCommand::Incrbyfloat,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "INFO",
    name: "info",
    cmd: RespCommand::Info,
    cats: RespAclCategories::from_bits_retain(0x10010),
    parent: None,
  },
  CmdEntry {
    cs: "KEYS",
    name: "keys",
    cmd: RespCommand::Keys,
    cats: RespAclCategories::from_bits_retain(0x11210),
    parent: None,
  },
  CmdEntry {
    cs: "LASTSAVE",
    name: "lastsave",
    cmd: RespCommand::Lastsave,
    cats: RespAclCategories::from_bits_retain(0x111),
    parent: None,
  },
  CmdEntry {
    cs: "LATENCY",
    name: "latency",
    cmd: RespCommand::Latency,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "LATENCY_HELP",
    name: "latency|help",
    cmd: RespCommand::LatencyHelp,
    cats: RespAclCategories::from_bits_retain(0x210000),
    parent: Some(RespCommand::Latency),
  },
  CmdEntry {
    cs: "LATENCY_HISTOGRAM",
    name: "latency|histogram",
    cmd: RespCommand::LatencyHistogram,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Latency),
  },
  CmdEntry {
    cs: "LATENCY_RESET",
    name: "latency|reset",
    cmd: RespCommand::LatencyReset,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Latency),
  },
  CmdEntry {
    cs: "LCS",
    name: "lcs",
    cmd: RespCommand::Lcs,
    cats: RespAclCategories::from_bits_retain(0x51000),
    parent: None,
  },
  CmdEntry {
    cs: "LINDEX",
    name: "lindex",
    cmd: RespCommand::Lindex,
    cats: RespAclCategories::from_bits_retain(0x11400),
    parent: None,
  },
  CmdEntry {
    cs: "LINSERT",
    name: "linsert",
    cmd: RespCommand::Linsert,
    cats: RespAclCategories::from_bits_retain(0x110400),
    parent: None,
  },
  CmdEntry {
    cs: "LLEN",
    name: "llen",
    cmd: RespCommand::Llen,
    cats: RespAclCategories::from_bits_retain(0x1500),
    parent: None,
  },
  CmdEntry {
    cs: "LMOVE",
    name: "lmove",
    cmd: RespCommand::Lmove,
    cats: RespAclCategories::from_bits_retain(0x110400),
    parent: None,
  },
  CmdEntry {
    cs: "LMPOP",
    name: "lmpop",
    cmd: RespCommand::Lmpop,
    cats: RespAclCategories::from_bits_retain(0x110400),
    parent: None,
  },
  CmdEntry {
    cs: "LPOP",
    name: "lpop",
    cmd: RespCommand::Lpop,
    cats: RespAclCategories::from_bits_retain(0x100500),
    parent: None,
  },
  CmdEntry {
    cs: "LPOS",
    name: "lpos",
    cmd: RespCommand::Lpos,
    cats: RespAclCategories::from_bits_retain(0x11400),
    parent: None,
  },
  CmdEntry {
    cs: "LPUSH",
    name: "lpush",
    cmd: RespCommand::Lpush,
    cats: RespAclCategories::from_bits_retain(0x100500),
    parent: None,
  },
  CmdEntry {
    cs: "LPUSHX",
    name: "lpushx",
    cmd: RespCommand::Lpushx,
    cats: RespAclCategories::from_bits_retain(0x100500),
    parent: None,
  },
  CmdEntry {
    cs: "LRANGE",
    name: "lrange",
    cmd: RespCommand::Lrange,
    cats: RespAclCategories::from_bits_retain(0x11400),
    parent: None,
  },
  CmdEntry {
    cs: "LREM",
    name: "lrem",
    cmd: RespCommand::Lrem,
    cats: RespAclCategories::from_bits_retain(0x110400),
    parent: None,
  },
  CmdEntry {
    cs: "LSET",
    name: "lset",
    cmd: RespCommand::Lset,
    cats: RespAclCategories::from_bits_retain(0x110400),
    parent: None,
  },
  CmdEntry {
    cs: "LTRIM",
    name: "ltrim",
    cmd: RespCommand::Ltrim,
    cats: RespAclCategories::from_bits_retain(0x110400),
    parent: None,
  },
  CmdEntry {
    cs: "MEMORY",
    name: "memory",
    cmd: RespCommand::Memory,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "MEMORY_USAGE",
    name: "memory|usage",
    cmd: RespCommand::MemoryUsage,
    cats: RespAclCategories::from_bits_retain(0x11000),
    parent: Some(RespCommand::Memory),
  },
  CmdEntry {
    cs: "MGET",
    name: "mget",
    cmd: RespCommand::Mget,
    cats: RespAclCategories::from_bits_retain(0x41100),
    parent: None,
  },
  CmdEntry {
    cs: "MIGRATE",
    name: "migrate",
    cmd: RespCommand::Migrate,
    cats: RespAclCategories::from_bits_retain(0x110210),
    parent: None,
  },
  CmdEntry {
    cs: "MODULE",
    name: "module",
    cmd: RespCommand::Module,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: None,
  },
  CmdEntry {
    cs: "MODULE_LOADCS",
    name: "module|loadcs",
    cmd: RespCommand::ModuleLoadcs,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Module),
  },
  CmdEntry {
    cs: "MONITOR",
    name: "monitor",
    cmd: RespCommand::Monitor,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: None,
  },
  CmdEntry {
    cs: "MSET",
    name: "mset",
    cmd: RespCommand::Mset,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "MSETNX",
    name: "msetnx",
    cmd: RespCommand::Msetnx,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "MULTI",
    name: "multi",
    cmd: RespCommand::Multi,
    cats: RespAclCategories::from_bits_retain(0x80100),
    parent: None,
  },
  CmdEntry {
    cs: "OBJECT",
    name: "object",
    cmd: RespCommand::Object,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "OBJECT_ENCODING",
    name: "object|encoding",
    cmd: RespCommand::ObjectEncoding,
    cats: RespAclCategories::from_bits_retain(0x11200),
    parent: Some(RespCommand::Object),
  },
  CmdEntry {
    cs: "OBJECT_FREQ",
    name: "object|freq",
    cmd: RespCommand::ObjectFreq,
    cats: RespAclCategories::from_bits_retain(0x11200),
    parent: Some(RespCommand::Object),
  },
  CmdEntry {
    cs: "OBJECT_HELP",
    name: "object|help",
    cmd: RespCommand::ObjectHelp,
    cats: RespAclCategories::from_bits_retain(0x10200),
    parent: Some(RespCommand::Object),
  },
  CmdEntry {
    cs: "OBJECT_IDLETIME",
    name: "object|idletime",
    cmd: RespCommand::ObjectIdletime,
    cats: RespAclCategories::from_bits_retain(0x11200),
    parent: Some(RespCommand::Object),
  },
  CmdEntry {
    cs: "OBJECT_REFCOUNT",
    name: "object|refcount",
    cmd: RespCommand::ObjectRefcount,
    cats: RespAclCategories::from_bits_retain(0x11200),
    parent: Some(RespCommand::Object),
  },
  CmdEntry {
    cs: "PERSIST",
    name: "persist",
    cmd: RespCommand::Persist,
    cats: RespAclCategories::from_bits_retain(0x100300),
    parent: None,
  },
  CmdEntry {
    cs: "PEXPIRE",
    name: "pexpire",
    cmd: RespCommand::Pexpire,
    cats: RespAclCategories::from_bits_retain(0x100300),
    parent: None,
  },
  CmdEntry {
    cs: "PEXPIREAT",
    name: "pexpireat",
    cmd: RespCommand::Pexpireat,
    cats: RespAclCategories::from_bits_retain(0x100300),
    parent: None,
  },
  CmdEntry {
    cs: "PEXPIRETIME",
    name: "pexpiretime",
    cmd: RespCommand::Pexpiretime,
    cats: RespAclCategories::from_bits_retain(0x1300),
    parent: None,
  },
  CmdEntry {
    cs: "PFADD",
    name: "pfadd",
    cmd: RespCommand::Pfadd,
    cats: RespAclCategories::from_bits_retain(0x100180),
    parent: None,
  },
  CmdEntry {
    cs: "PFCOUNT",
    name: "pfcount",
    cmd: RespCommand::Pfcount,
    cats: RespAclCategories::from_bits_retain(0x11080),
    parent: None,
  },
  CmdEntry {
    cs: "PFMERGE",
    name: "pfmerge",
    cmd: RespCommand::Pfmerge,
    cats: RespAclCategories::from_bits_retain(0x110080),
    parent: None,
  },
  CmdEntry {
    cs: "PING",
    name: "ping",
    cmd: RespCommand::Ping,
    cats: RespAclCategories::from_bits_retain(0x108),
    parent: None,
  },
  CmdEntry {
    cs: "PSETEX",
    name: "psetex",
    cmd: RespCommand::Psetex,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "PSUBSCRIBE",
    name: "psubscribe",
    cmd: RespCommand::Psubscribe,
    cats: RespAclCategories::from_bits_retain(0x10800),
    parent: None,
  },
  CmdEntry {
    cs: "PTTL",
    name: "pttl",
    cmd: RespCommand::Pttl,
    cats: RespAclCategories::from_bits_retain(0x1300),
    parent: None,
  },
  CmdEntry {
    cs: "PUBLISH",
    name: "publish",
    cmd: RespCommand::Publish,
    cats: RespAclCategories::from_bits_retain(0x900),
    parent: None,
  },
  CmdEntry {
    cs: "PUBSUB",
    name: "pubsub",
    cmd: RespCommand::Pubsub,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "PUBSUB_CHANNELS",
    name: "pubsub|channels",
    cmd: RespCommand::PubsubChannels,
    cats: RespAclCategories::from_bits_retain(0x10800),
    parent: Some(RespCommand::Pubsub),
  },
  CmdEntry {
    cs: "PUBSUB_NUMPAT",
    name: "pubsub|numpat",
    cmd: RespCommand::PubsubNumpat,
    cats: RespAclCategories::from_bits_retain(0x10800),
    parent: Some(RespCommand::Pubsub),
  },
  CmdEntry {
    cs: "PUBSUB_NUMSUB",
    name: "pubsub|numsub",
    cmd: RespCommand::PubsubNumsub,
    cats: RespAclCategories::from_bits_retain(0x10800),
    parent: Some(RespCommand::Pubsub),
  },
  CmdEntry {
    cs: "PUNSUBSCRIBE",
    name: "punsubscribe",
    cmd: RespCommand::Punsubscribe,
    cats: RespAclCategories::from_bits_retain(0x10800),
    parent: None,
  },
  CmdEntry {
    cs: "QUIT",
    name: "quit",
    cmd: RespCommand::Quit,
    cats: RespAclCategories::from_bits_retain(0x108),
    parent: None,
  },
  CmdEntry {
    cs: "READONLY",
    name: "readonly",
    cmd: RespCommand::Readonly,
    cats: RespAclCategories::from_bits_retain(0x108),
    parent: None,
  },
  CmdEntry {
    cs: "READWRITE",
    name: "readwrite",
    cmd: RespCommand::Readwrite,
    cats: RespAclCategories::from_bits_retain(0x108),
    parent: None,
  },
  CmdEntry {
    cs: "REGISTERCS",
    name: "registercs",
    cmd: RespCommand::Registercs,
    cats: RespAclCategories::from_bits_retain(0x200011),
    parent: None,
  },
  CmdEntry {
    cs: "RENAME",
    name: "rename",
    cmd: RespCommand::Rename,
    cats: RespAclCategories::from_bits_retain(0x110200),
    parent: None,
  },
  CmdEntry {
    cs: "RENAMENX",
    name: "renamenx",
    cmd: RespCommand::Renamenx,
    cats: RespAclCategories::from_bits_retain(0x100300),
    parent: None,
  },
  CmdEntry {
    cs: "REPLICAOF",
    name: "replicaof",
    cmd: RespCommand::Replicaof,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: None,
  },
  CmdEntry {
    cs: "RESTORE",
    name: "restore",
    cmd: RespCommand::Restore,
    cats: RespAclCategories::from_bits_retain(0x110210),
    parent: None,
  },
  CmdEntry {
    cs: "RICONFIG",
    name: "ri.config",
    cmd: RespCommand::Riconfig,
    cats: RespAclCategories::from_bits_retain(0x201100),
    parent: None,
  },
  CmdEntry {
    cs: "RICREATE",
    name: "ri.create",
    cmd: RespCommand::Ricreate,
    cats: RespAclCategories::from_bits_retain(0x310000),
    parent: None,
  },
  CmdEntry {
    cs: "RIDEL",
    name: "ri.del",
    cmd: RespCommand::Ridel,
    cats: RespAclCategories::from_bits_retain(0x300100),
    parent: None,
  },
  CmdEntry {
    cs: "RIEXISTS",
    name: "ri.exists",
    cmd: RespCommand::Riexists,
    cats: RespAclCategories::from_bits_retain(0x201100),
    parent: None,
  },
  CmdEntry {
    cs: "RIGET",
    name: "ri.get",
    cmd: RespCommand::Riget,
    cats: RespAclCategories::from_bits_retain(0x201100),
    parent: None,
  },
  CmdEntry {
    cs: "RIMETRICS",
    name: "ri.metrics",
    cmd: RespCommand::Rimetrics,
    cats: RespAclCategories::from_bits_retain(0x201100),
    parent: None,
  },
  CmdEntry {
    cs: "RIRANGE",
    name: "ri.range",
    cmd: RespCommand::Rirange,
    cats: RespAclCategories::from_bits_retain(0x211000),
    parent: None,
  },
  CmdEntry {
    cs: "RISCAN",
    name: "ri.scan",
    cmd: RespCommand::Riscan,
    cats: RespAclCategories::from_bits_retain(0x211000),
    parent: None,
  },
  CmdEntry {
    cs: "RISET",
    name: "ri.set",
    cmd: RespCommand::Riset,
    cats: RespAclCategories::from_bits_retain(0x300100),
    parent: None,
  },
  CmdEntry {
    cs: "ROLE",
    name: "role",
    cmd: RespCommand::Role,
    cats: RespAclCategories::from_bits_retain(0x111),
    parent: None,
  },
  CmdEntry {
    cs: "RPOP",
    name: "rpop",
    cmd: RespCommand::Rpop,
    cats: RespAclCategories::from_bits_retain(0x100500),
    parent: None,
  },
  CmdEntry {
    cs: "RPOPLPUSH",
    name: "rpoplpush",
    cmd: RespCommand::Rpoplpush,
    cats: RespAclCategories::from_bits_retain(0x110400),
    parent: None,
  },
  CmdEntry {
    cs: "RPUSH",
    name: "rpush",
    cmd: RespCommand::Rpush,
    cats: RespAclCategories::from_bits_retain(0x100500),
    parent: None,
  },
  CmdEntry {
    cs: "RPUSHX",
    name: "rpushx",
    cmd: RespCommand::Rpushx,
    cats: RespAclCategories::from_bits_retain(0x100500),
    parent: None,
  },
  CmdEntry {
    cs: "RUNTXP",
    name: "runtxp",
    cmd: RespCommand::Runtxp,
    cats: RespAclCategories::from_bits_retain(0x280000),
    parent: None,
  },
  CmdEntry {
    cs: "SADD",
    name: "sadd",
    cmd: RespCommand::Sadd,
    cats: RespAclCategories::from_bits_retain(0x104100),
    parent: None,
  },
  CmdEntry {
    cs: "SAVE",
    name: "save",
    cmd: RespCommand::Save,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: None,
  },
  CmdEntry {
    cs: "SCAN",
    name: "scan",
    cmd: RespCommand::Scan,
    cats: RespAclCategories::from_bits_retain(0x11200),
    parent: None,
  },
  CmdEntry {
    cs: "SCARD",
    name: "scard",
    cmd: RespCommand::Scard,
    cats: RespAclCategories::from_bits_retain(0x5100),
    parent: None,
  },
  CmdEntry {
    cs: "SCRIPT",
    name: "script",
    cmd: RespCommand::Script,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "SCRIPT_EXISTS",
    name: "script|exists",
    cmd: RespCommand::ScriptExists,
    cats: RespAclCategories::from_bits_retain(0x12000),
    parent: Some(RespCommand::Script),
  },
  CmdEntry {
    cs: "SCRIPT_FLUSH",
    name: "script|flush",
    cmd: RespCommand::ScriptFlush,
    cats: RespAclCategories::from_bits_retain(0x12000),
    parent: Some(RespCommand::Script),
  },
  CmdEntry {
    cs: "SCRIPT_LOAD",
    name: "script|load",
    cmd: RespCommand::ScriptLoad,
    cats: RespAclCategories::from_bits_retain(0x12000),
    parent: Some(RespCommand::Script),
  },
  CmdEntry {
    cs: "SDIFF",
    name: "sdiff",
    cmd: RespCommand::Sdiff,
    cats: RespAclCategories::from_bits_retain(0x15000),
    parent: None,
  },
  CmdEntry {
    cs: "SDIFFSTORE",
    name: "sdiffstore",
    cmd: RespCommand::Sdiffstore,
    cats: RespAclCategories::from_bits_retain(0x114000),
    parent: None,
  },
  CmdEntry {
    cs: "SECONDARYOF",
    name: "secondaryof",
    cmd: RespCommand::Secondaryof,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: None,
  },
  CmdEntry {
    cs: "SELECT",
    name: "select",
    cmd: RespCommand::Select,
    cats: RespAclCategories::from_bits_retain(0x108),
    parent: None,
  },
  CmdEntry {
    cs: "SET",
    name: "set",
    cmd: RespCommand::Set,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "SETBIT",
    name: "setbit",
    cmd: RespCommand::Setbit,
    cats: RespAclCategories::from_bits_retain(0x110002),
    parent: None,
  },
  CmdEntry {
    cs: "SETEX",
    name: "setex",
    cmd: RespCommand::Setex,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "SETIFGREATER",
    name: "setifgreater",
    cmd: RespCommand::Setifgreater,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "SETIFMATCH",
    name: "setifmatch",
    cmd: RespCommand::Setifmatch,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "SETNX",
    name: "setnx",
    cmd: RespCommand::Setnx,
    cats: RespAclCategories::from_bits_retain(0x140100),
    parent: None,
  },
  CmdEntry {
    cs: "SETRANGE",
    name: "setrange",
    cmd: RespCommand::Setrange,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "SETWITHETAG",
    name: "setwithetag",
    cmd: RespCommand::Setwithetag,
    cats: RespAclCategories::from_bits_retain(0x150000),
    parent: None,
  },
  CmdEntry {
    cs: "SINTER",
    name: "sinter",
    cmd: RespCommand::Sinter,
    cats: RespAclCategories::from_bits_retain(0x15000),
    parent: None,
  },
  CmdEntry {
    cs: "SINTERCARD",
    name: "sintercard",
    cmd: RespCommand::Sintercard,
    cats: RespAclCategories::from_bits_retain(0x15000),
    parent: None,
  },
  CmdEntry {
    cs: "SINTERSTORE",
    name: "sinterstore",
    cmd: RespCommand::Sinterstore,
    cats: RespAclCategories::from_bits_retain(0x114000),
    parent: None,
  },
  CmdEntry {
    cs: "SISMEMBER",
    name: "sismember",
    cmd: RespCommand::Sismember,
    cats: RespAclCategories::from_bits_retain(0x5100),
    parent: None,
  },
  CmdEntry {
    cs: "SECONDARYOF",
    name: "slaveof",
    cmd: RespCommand::Secondaryof,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: None,
  },
  CmdEntry {
    cs: "SLOWLOG",
    name: "slowlog",
    cmd: RespCommand::Slowlog,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: None,
  },
  CmdEntry {
    cs: "SLOWLOG_GET",
    name: "slowlog|get",
    cmd: RespCommand::SlowlogGet,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Slowlog),
  },
  CmdEntry {
    cs: "SLOWLOG_HELP",
    name: "slowlog|help",
    cmd: RespCommand::SlowlogHelp,
    cats: RespAclCategories::from_bits_retain(0x10000),
    parent: Some(RespCommand::Slowlog),
  },
  CmdEntry {
    cs: "SLOWLOG_LEN",
    name: "slowlog|len",
    cmd: RespCommand::SlowlogLen,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Slowlog),
  },
  CmdEntry {
    cs: "SLOWLOG_RESET",
    name: "slowlog|reset",
    cmd: RespCommand::SlowlogReset,
    cats: RespAclCategories::from_bits_retain(0x10011),
    parent: Some(RespCommand::Slowlog),
  },
  CmdEntry {
    cs: "SMEMBERS",
    name: "smembers",
    cmd: RespCommand::Smembers,
    cats: RespAclCategories::from_bits_retain(0x15000),
    parent: None,
  },
  CmdEntry {
    cs: "SMISMEMBER",
    name: "smismember",
    cmd: RespCommand::Smismember,
    cats: RespAclCategories::from_bits_retain(0x5100),
    parent: None,
  },
  CmdEntry {
    cs: "SMOVE",
    name: "smove",
    cmd: RespCommand::Smove,
    cats: RespAclCategories::from_bits_retain(0x104100),
    parent: None,
  },
  CmdEntry {
    cs: "SPOP",
    name: "spop",
    cmd: RespCommand::Spop,
    cats: RespAclCategories::from_bits_retain(0x104100),
    parent: None,
  },
  CmdEntry {
    cs: "SPUBLISH",
    name: "spublish",
    cmd: RespCommand::Spublish,
    cats: RespAclCategories::from_bits_retain(0x11800),
    parent: None,
  },
  CmdEntry {
    cs: "SRANDMEMBER",
    name: "srandmember",
    cmd: RespCommand::Srandmember,
    cats: RespAclCategories::from_bits_retain(0x15000),
    parent: None,
  },
  CmdEntry {
    cs: "SREM",
    name: "srem",
    cmd: RespCommand::Srem,
    cats: RespAclCategories::from_bits_retain(0x104100),
    parent: None,
  },
  CmdEntry {
    cs: "SSCAN",
    name: "sscan",
    cmd: RespCommand::Sscan,
    cats: RespAclCategories::from_bits_retain(0x15000),
    parent: None,
  },
  CmdEntry {
    cs: "SSUBSCRIBE",
    name: "ssubscribe",
    cmd: RespCommand::Ssubscribe,
    cats: RespAclCategories::from_bits_retain(0x11800),
    parent: None,
  },
  CmdEntry {
    cs: "STRLEN",
    name: "strlen",
    cmd: RespCommand::Strlen,
    cats: RespAclCategories::from_bits_retain(0x41100),
    parent: None,
  },
  CmdEntry {
    cs: "SUBSCRIBE",
    name: "subscribe",
    cmd: RespCommand::Subscribe,
    cats: RespAclCategories::from_bits_retain(0x10800),
    parent: None,
  },
  CmdEntry {
    cs: "SUBSTR",
    name: "substr",
    cmd: RespCommand::Substr,
    cats: RespAclCategories::from_bits_retain(0x51000),
    parent: None,
  },
  CmdEntry {
    cs: "SUNION",
    name: "sunion",
    cmd: RespCommand::Sunion,
    cats: RespAclCategories::from_bits_retain(0x15000),
    parent: None,
  },
  CmdEntry {
    cs: "SUNIONSTORE",
    name: "sunionstore",
    cmd: RespCommand::Sunionstore,
    cats: RespAclCategories::from_bits_retain(0x114000),
    parent: None,
  },
  CmdEntry {
    cs: "SWAPDB",
    name: "swapdb",
    cmd: RespCommand::Swapdb,
    cats: RespAclCategories::from_bits_retain(0x100310),
    parent: None,
  },
  CmdEntry {
    cs: "TIME",
    name: "time",
    cmd: RespCommand::Time,
    cats: RespAclCategories::from_bits_retain(0x100),
    parent: None,
  },
  CmdEntry {
    cs: "TTL",
    name: "ttl",
    cmd: RespCommand::Ttl,
    cats: RespAclCategories::from_bits_retain(0x1300),
    parent: None,
  },
  CmdEntry {
    cs: "TYPE",
    name: "type",
    cmd: RespCommand::Type,
    cats: RespAclCategories::from_bits_retain(0x1300),
    parent: None,
  },
  CmdEntry {
    cs: "UNLINK",
    name: "unlink",
    cmd: RespCommand::Unlink,
    cats: RespAclCategories::from_bits_retain(0x100300),
    parent: None,
  },
  CmdEntry {
    cs: "UNSUBSCRIBE",
    name: "unsubscribe",
    cmd: RespCommand::Unsubscribe,
    cats: RespAclCategories::from_bits_retain(0x10800),
    parent: None,
  },
  CmdEntry {
    cs: "UNWATCH",
    name: "unwatch",
    cmd: RespCommand::Unwatch,
    cats: RespAclCategories::from_bits_retain(0x80100),
    parent: None,
  },
  CmdEntry {
    cs: "VADD",
    name: "vadd",
    cmd: RespCommand::Vadd,
    cats: RespAclCategories::from_bits_retain(0x900100),
    parent: None,
  },
  CmdEntry {
    cs: "VCARD",
    name: "vcard",
    cmd: RespCommand::Vcard,
    cats: RespAclCategories::from_bits_retain(0x801100),
    parent: None,
  },
  CmdEntry {
    cs: "VDIM",
    name: "vdim",
    cmd: RespCommand::Vdim,
    cats: RespAclCategories::from_bits_retain(0x801100),
    parent: None,
  },
  CmdEntry {
    cs: "VEMB",
    name: "vemb",
    cmd: RespCommand::Vemb,
    cats: RespAclCategories::from_bits_retain(0x801100),
    parent: None,
  },
  CmdEntry {
    cs: "VGETATTR",
    name: "vgetattr",
    cmd: RespCommand::Vgetattr,
    cats: RespAclCategories::from_bits_retain(0x801100),
    parent: None,
  },
  CmdEntry {
    cs: "VINFO",
    name: "vinfo",
    cmd: RespCommand::Vinfo,
    cats: RespAclCategories::from_bits_retain(0x801100),
    parent: None,
  },
  CmdEntry {
    cs: "VISMEMBER",
    name: "vismember",
    cmd: RespCommand::Vismember,
    cats: RespAclCategories::from_bits_retain(0x801100),
    parent: None,
  },
  CmdEntry {
    cs: "VLINKS",
    name: "vlinks",
    cmd: RespCommand::Vlinks,
    cats: RespAclCategories::from_bits_retain(0x801100),
    parent: None,
  },
  CmdEntry {
    cs: "VRANDMEMBER",
    name: "vrandmember",
    cmd: RespCommand::Vrandmember,
    cats: RespAclCategories::from_bits_retain(0x811000),
    parent: None,
  },
  CmdEntry {
    cs: "VREM",
    name: "vrem",
    cmd: RespCommand::Vrem,
    cats: RespAclCategories::from_bits_retain(0x910000),
    parent: None,
  },
  CmdEntry {
    cs: "VSETATTR",
    name: "vsetattr",
    cmd: RespCommand::Vsetattr,
    cats: RespAclCategories::from_bits_retain(0x900100),
    parent: None,
  },
  CmdEntry {
    cs: "VSIM",
    name: "vsim",
    cmd: RespCommand::Vsim,
    cats: RespAclCategories::from_bits_retain(0x811000),
    parent: None,
  },
  CmdEntry {
    cs: "WATCH",
    name: "watch",
    cmd: RespCommand::Watch,
    cats: RespAclCategories::from_bits_retain(0x81100),
    parent: None,
  },
  CmdEntry {
    cs: "WATCHMS",
    name: "watchms",
    cmd: RespCommand::Watchms,
    cats: RespAclCategories::from_bits_retain(0x81100),
    parent: None,
  },
  CmdEntry {
    cs: "WATCHOS",
    name: "watchos",
    cmd: RespCommand::Watchos,
    cats: RespAclCategories::from_bits_retain(0x81100),
    parent: None,
  },
  CmdEntry {
    cs: "ZADD",
    name: "zadd",
    cmd: RespCommand::Zadd,
    cats: RespAclCategories::from_bits_retain(0x108100),
    parent: None,
  },
  CmdEntry {
    cs: "ZCARD",
    name: "zcard",
    cmd: RespCommand::Zcard,
    cats: RespAclCategories::from_bits_retain(0x9100),
    parent: None,
  },
  CmdEntry {
    cs: "ZCOLLECT",
    name: "zcollect",
    cmd: RespCommand::Zcollect,
    cats: RespAclCategories::from_bits_retain(0x308001),
    parent: None,
  },
  CmdEntry {
    cs: "ZCOUNT",
    name: "zcount",
    cmd: RespCommand::Zcount,
    cats: RespAclCategories::from_bits_retain(0x9100),
    parent: None,
  },
  CmdEntry {
    cs: "ZDIFF",
    name: "zdiff",
    cmd: RespCommand::Zdiff,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZDIFFSTORE",
    name: "zdiffstore",
    cmd: RespCommand::Zdiffstore,
    cats: RespAclCategories::from_bits_retain(0x118000),
    parent: None,
  },
  CmdEntry {
    cs: "ZEXPIRE",
    name: "zexpire",
    cmd: RespCommand::Zexpire,
    cats: RespAclCategories::from_bits_retain(0x308100),
    parent: None,
  },
  CmdEntry {
    cs: "ZEXPIREAT",
    name: "zexpireat",
    cmd: RespCommand::Zexpireat,
    cats: RespAclCategories::from_bits_retain(0x308100),
    parent: None,
  },
  CmdEntry {
    cs: "ZEXPIRETIME",
    name: "zexpiretime",
    cmd: RespCommand::Zexpiretime,
    cats: RespAclCategories::from_bits_retain(0x209100),
    parent: None,
  },
  CmdEntry {
    cs: "ZINCRBY",
    name: "zincrby",
    cmd: RespCommand::Zincrby,
    cats: RespAclCategories::from_bits_retain(0x108100),
    parent: None,
  },
  CmdEntry {
    cs: "ZINTER",
    name: "zinter",
    cmd: RespCommand::Zinter,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZINTERCARD",
    name: "zintercard",
    cmd: RespCommand::Zintercard,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZINTERSTORE",
    name: "zinterstore",
    cmd: RespCommand::Zinterstore,
    cats: RespAclCategories::from_bits_retain(0x118000),
    parent: None,
  },
  CmdEntry {
    cs: "ZLEXCOUNT",
    name: "zlexcount",
    cmd: RespCommand::Zlexcount,
    cats: RespAclCategories::from_bits_retain(0x9100),
    parent: None,
  },
  CmdEntry {
    cs: "ZMPOP",
    name: "zmpop",
    cmd: RespCommand::Zmpop,
    cats: RespAclCategories::from_bits_retain(0x118000),
    parent: None,
  },
  CmdEntry {
    cs: "ZMSCORE",
    name: "zmscore",
    cmd: RespCommand::Zmscore,
    cats: RespAclCategories::from_bits_retain(0x9100),
    parent: None,
  },
  CmdEntry {
    cs: "ZPERSIST",
    name: "zpersist",
    cmd: RespCommand::Zpersist,
    cats: RespAclCategories::from_bits_retain(0x308100),
    parent: None,
  },
  CmdEntry {
    cs: "ZPEXPIRE",
    name: "zpexpire",
    cmd: RespCommand::Zpexpire,
    cats: RespAclCategories::from_bits_retain(0x308100),
    parent: None,
  },
  CmdEntry {
    cs: "ZPEXPIREAT",
    name: "zpexpireat",
    cmd: RespCommand::Zpexpireat,
    cats: RespAclCategories::from_bits_retain(0x308100),
    parent: None,
  },
  CmdEntry {
    cs: "ZPEXPIRETIME",
    name: "zpexpiretime",
    cmd: RespCommand::Zpexpiretime,
    cats: RespAclCategories::from_bits_retain(0x209100),
    parent: None,
  },
  CmdEntry {
    cs: "ZPOPMAX",
    name: "zpopmax",
    cmd: RespCommand::Zpopmax,
    cats: RespAclCategories::from_bits_retain(0x108100),
    parent: None,
  },
  CmdEntry {
    cs: "ZPOPMIN",
    name: "zpopmin",
    cmd: RespCommand::Zpopmin,
    cats: RespAclCategories::from_bits_retain(0x108100),
    parent: None,
  },
  CmdEntry {
    cs: "ZPTTL",
    name: "zpttl",
    cmd: RespCommand::Zpttl,
    cats: RespAclCategories::from_bits_retain(0x209100),
    parent: None,
  },
  CmdEntry {
    cs: "ZRANDMEMBER",
    name: "zrandmember",
    cmd: RespCommand::Zrandmember,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZRANGE",
    name: "zrange",
    cmd: RespCommand::Zrange,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZRANGEBYLEX",
    name: "zrangebylex",
    cmd: RespCommand::Zrangebylex,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZRANGEBYSCORE",
    name: "zrangebyscore",
    cmd: RespCommand::Zrangebyscore,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZRANGESTORE",
    name: "zrangestore",
    cmd: RespCommand::Zrangestore,
    cats: RespAclCategories::from_bits_retain(0x118000),
    parent: None,
  },
  CmdEntry {
    cs: "ZRANK",
    name: "zrank",
    cmd: RespCommand::Zrank,
    cats: RespAclCategories::from_bits_retain(0x9100),
    parent: None,
  },
  CmdEntry {
    cs: "ZREM",
    name: "zrem",
    cmd: RespCommand::Zrem,
    cats: RespAclCategories::from_bits_retain(0x108100),
    parent: None,
  },
  CmdEntry {
    cs: "ZREMRANGEBYLEX",
    name: "zremrangebylex",
    cmd: RespCommand::Zremrangebylex,
    cats: RespAclCategories::from_bits_retain(0x118000),
    parent: None,
  },
  CmdEntry {
    cs: "ZREMRANGEBYRANK",
    name: "zremrangebyrank",
    cmd: RespCommand::Zremrangebyrank,
    cats: RespAclCategories::from_bits_retain(0x118000),
    parent: None,
  },
  CmdEntry {
    cs: "ZREMRANGEBYSCORE",
    name: "zremrangebyscore",
    cmd: RespCommand::Zremrangebyscore,
    cats: RespAclCategories::from_bits_retain(0x118000),
    parent: None,
  },
  CmdEntry {
    cs: "ZREVRANGE",
    name: "zrevrange",
    cmd: RespCommand::Zrevrange,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZREVRANGEBYLEX",
    name: "zrevrangebylex",
    cmd: RespCommand::Zrevrangebylex,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZREVRANGEBYSCORE",
    name: "zrevrangebyscore",
    cmd: RespCommand::Zrevrangebyscore,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZREVRANK",
    name: "zrevrank",
    cmd: RespCommand::Zrevrank,
    cats: RespAclCategories::from_bits_retain(0x9100),
    parent: None,
  },
  CmdEntry {
    cs: "ZSCAN",
    name: "zscan",
    cmd: RespCommand::Zscan,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZSCORE",
    name: "zscore",
    cmd: RespCommand::Zscore,
    cats: RespAclCategories::from_bits_retain(0x9100),
    parent: None,
  },
  CmdEntry {
    cs: "ZTTL",
    name: "zttl",
    cmd: RespCommand::Zttl,
    cats: RespAclCategories::from_bits_retain(0x209100),
    parent: None,
  },
  CmdEntry {
    cs: "ZUNION",
    name: "zunion",
    cmd: RespCommand::Zunion,
    cats: RespAclCategories::from_bits_retain(0x19000),
    parent: None,
  },
  CmdEntry {
    cs: "ZUNIONSTORE",
    name: "zunionstore",
    cmd: RespCommand::Zunionstore,
    cats: RespAclCategories::from_bits_retain(0x118000),
    parent: None,
  },
];
