[package]
name = "wconf"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/wconf"
description = "Configuration options and runtime server configuration for wedb"

[lints]
workspace = true

[dependencies]
bitflags.workspace = true
itoa.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
wbase = { workspace = true }
wresp.workspace = true

[dev-dependencies]
aok.workspace = true
ctor.workspace = true
log_init.workspace = true
