[package]
name = "wdev"
version = "0.1.1"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/wdev"
description = "compio-powered async block device abstraction with segmented files / 基于 compio 的异步块设备抽象与分段文件"
keywords = ["async-io", "block-device", "storage", "compio", "segmented"]
categories = ["asynchronous", "filesystem", "database-implementations", "memory-management", "concurrency"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
compio-driver = { version = "0.12.5", default-features = false, features = ["sync"] }
futures-util = { workspace = true, default-features = false, features = ["alloc"] }
gxhash.workspace = true
itoa = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
papaya.workspace = true
thiserror = { workspace = true }
wbase = { workspace = true, features = ["align", "pool"] }

[dependencies.compio]
workspace = true
features = ["fs", "runtime"]

[dev-dependencies]
aok = { workspace = true }
ctor = { workspace = true }
log = { workspace = true }
log_init = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
