[package]
name = "wserver"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/webc-site/wedb.git"
homepage = "https://github.com/webc-site/wedb/tree/main/wserver"
description = "wserver"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-lock.workspace = true
bitflags = "2.13.1"
coarsetime.workspace = true
fastrand = "2.5.0"
gxhash = "3.5.0"
itoa.workspace = true
num_enum = "0.7.6"
papaya = "0.2.5"
parking_lot = "0.12.5"
thiserror = "2.0.20"
waof.workspace = true
wdev.workspace = true
wkv.workspace = true
wobject.workspace = true
wresp.workspace = true

[dev-dependencies]
aok = "0.1.18"
compio.workspace = true
ctor = "1.0.13"
log = "0.4.34"
log_init = "0.1.39"
tempfile.workspace = true

[lints]
workspace = true
