[package]
name = "windex"
version = "0.1.5"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/webc-site/wedb/tree/main/windex"
description = "Lock-free fixed-capacity hash index with overflow bucket pool"
keywords = ["hash-index", "lock-free", "hash-table", "storage-engine", "concurrency"]
categories = ["database-implementations", "data-structures", "concurrency", "algorithms", "memory-management"]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
memmap2 = "0.9.11"
page_size = "0.6.0"
thiserror = { workspace = true }
wbase = { features = ["addr", "backoff", "error", "striped", "thread"], workspace = true }
whasher.workspace = true

[dev-dependencies]
aok = { workspace = true }
ctor = { workspace = true }
log.workspace = true
log_init = { workspace = true }
parking_lot.workspace = true

[lints]
workspace = true
